### ISSUE TITLE
firefox54.0.1+greasemonkey3.17 不生效?

### ISSUE THREAD

**Issue by tooyangtoonaive** [tiansh/yawf#100]
![default](https://user-images.githubusercontent.com/19810827/41635152-c3b5e726-7479-11e8-9984-354df3af10e1.PNG)

**Comment by tiansh** [comment]
53 以后试试暴力猴。我这上个月把 52 升到 60 了，之前 52 加油猴很正常，不过据说 56 就完全不能用。（没用过 54 没什么印象了……）
