### ISSUE TITLE
使用此脚本后，首页视频无法播放

### ISSUE THREAD

**Issue by davidfromtheeast** [tiansh/yawf#103]
没用这个脚本的时候，首页视频能正常播放，点击控制，并且鼠标位于视频上时自动播放，一切正常。

开启此脚本后，首页视频无法播放，点击无反应，更不会自动播放了，并且视频上出现小窗口三个字，应该是此脚本附加的功能，但是点击小窗口后也只是空白小窗口，并没有视频。

设置里也没有与之相关的选项。我看了下FQA，里面说的HTML5播放器什么的，我这里设置里也根本没有。

win10系统，chrome浏览器。

**Comment by tiansh** [comment]
小窗口不是脚本带的功能，脚本懒得做这些功能。

首页用的是原版还是分组还是分组拼凑？开了小图功能吗？自动播放功能是开的还是关的？

**Comment by davidfromtheeast** [comment]
首页是原版，按作者隐藏。

小图是什么，没设置过相关的。

你说的自动播放是新浪本身的设置吗，我没动过，应该不算是自动播放，得鼠标滑到视频上方才开始自动播放。

我有点奇怪，我微博页面只开了这一个脚本，开了就有小窗口，不开就没没有，是哪里的问题。

**Comment by davidfromtheeast** [comment]
不知道是不是你已经解决了，反正我卸载脚本再安装了，现在没问题了。
