### ISSUE TITLE
能否添加禁用微博故事自动播放的功能+打包下载图片的文件名设为原图的文件名

### ISSUE THREAD

**Issue by tuanzi0630** [tiansh/yawf#105]
RT 每次刷到微博故事的视频就会自动播放 想完整的看一遍要等它放完后再重播就很麻烦

打包下载图片的文件名设为原图的文件名原因如下
有时候会忘记这些图有没有保存，但是如果是用原名命名解压到资料的文件夹里会提示有重名文件好查重

**Comment by tiansh** [comment]
我这网页上看不到微博故事，能够给个链接和截图。

打包下载目前没用原名是觉得这样对普通用户比较友好。这个可以考虑一下怎么做。

另外建议以后多个问题拆成两个帖子……

**Comment by tuanzi0630** [comment]
https://weibo.com/1774676624/GyhTd9TGf?from=page_1005051774676624_profile&wvr=6&mod=weibotime&type=comment#_rnd1536359160303
这是一条有微博故事的单独微博页面
点进旁边的微博故事连接是可以来回拖动进度条的

**Comment by tuanzi0630** [comment]
如果开启了点”开略缩图时直接查看原图功能“在微博信息流中点开微博故事会直接弹出原图网页
![d qn28e yt2buc 8 a gg](https://user-images.githubusercontent.com/42299911/45246119-27aa2980-b332-11e8-9e78-2756d8db49e9.png)

**Comment by tuanzi0630** [comment]
微博信息流中
![mg 6qqn2fp mihzvoh1r2k](https://user-images.githubusercontent.com/42299911/45246131-3a246300-b332-11e8-83b7-986b25159c74.png)

点开查看
![3 a cjlx6 vyr 9q7 3r k9](https://user-images.githubusercontent.com/42299911/45246155-5e803f80-b332-11e8-8bca-51042ae183c1.png)

点开链接可暂停/拖动进度条
![ut yf zy9i0m5 r0 a q](https://user-images.githubusercontent.com/42299911/45246180-7a83e100-b332-11e8-882e-e086bf738275.png)
