### ISSUE TITLE
建议整合视频加速播放模块和快捷键功能

### ISSUE THREAD

**Issue by luxiyourbro** [tiansh/yawf#106]
youtube的K暂停，J\L快进快退，F全屏，建议增加。整合视频加速播放功能。

**Comment by tiansh** [comment]
快捷键肯定得换一套：
* <kbd>K</kbd> 和 <kbd>J</kbd> ：上一条/下一条微博；
* <kbd>L</kbd>：点赞；
* <kbd>F</kbd>：转发；

还有就是这功能我用不上所以也懒得做，谁要是愿意做可以 PR 过来。（或者自己弄个别的插件啥的）

**Comment by luxiyourbro** [comment]
@tiansh 你真调皮

**Comment by tiansh** [comment]
视频替换回原生之后哪个插件愿意做哪个插件做好了，我这就不管了。
