### ISSUE TITLE
Safari 下无法读取分组

### ISSUE THREAD

**Issue by palooney** [tiansh/yawf#107]
Safari 下一直无法读取分组，如图所示：
<img width="806" alt="screen shot 1" src="https://user-images.githubusercontent.com/9058204/44237260-77536600-a175-11e8-9764-b98b45f76045.png">

在无法读取分组的情况下，一登录微博之后首页是空白的，但是多刷新几次之后主页就有微博了，不知道是怎么回事_(:з」∠)_

不知道有什么解决方法吗？谢谢！

**Comment by tiansh** [comment]
我不知道，我这没 Safari 。重装之类的试试，不行我也不知道怎么回事。谁知道怎么回事的欢迎修一下。

**Comment by tiansh** [comment]
据称如果设置的组织 cookies 之类的会有这类情况。总之我这应该没法处理 safari，而且后面的版本很可能也跑不起来。
