### ISSUE TITLE
首页出现了一个“来自“兴趣推荐””，希望能够屏蔽

### ISSUE THREAD

**Issue by szy912** [tiansh/yawf#110]

**Comment by tiansh** [comment]
我没看到类似的情况。请确认一下“更多”选项卡下的“隐藏以下微博 - 广告/商品”和“隐藏以下微博 - 推荐”是否全都开了。“版面清理”下的“隐藏模块 - 中栏”里面的“微博兴趣推荐（顶部）”是不是开了。如果这些选项都已经打开了（打开之后记得刷新页面）还有问题，麻烦发个截图上来让我看看是什么。

**Comment by f1ume** [comment]
隐藏推荐的选项一直开的
但是首页依然加插来自 兴趣推荐 的东西
![default](https://user-images.githubusercontent.com/39055042/44961988-db837180-af4c-11e8-91e3-c6c4c7bfa3f3.jpg)
这个号我没关注。
前几天更过分，没有新微博，首页直接全是这种兴趣推荐的。
这两天才收敛一点。偶尔加插一两条

**Comment by tiansh** [comment]
这边暂时无法确认，不过据说关注的人发的东西比较少的话可能会遇到这个。暂时可以打开“分组代替首页”功能试试，应该可以解决。如果作者这边能亲眼看到这个问题会尽快处理。
