### ISSUE TITLE
插件导致部分微博不显示

### ISSUE THREAD

**Issue by ShimotsukiH** [tiansh/yawf#113]
如图 我发现打开插件的时候  有个我关注的人的微博内容不显示 
https://weibo.com/cnocg?profile_ftype=1&is_all=1#_0

![image](https://user-images.githubusercontent.com/33424662/46993684-20e9b000-d143-11e8-85ee-25fa26035840.png)
![image](https://user-images.githubusercontent.com/33424662/46993693-34951680-d143-11e8-911d-ae0955c9abe6.png)

https://www.iloveimg.com/zh-cn/download/znA0zvpn3bb23t6mctAmzrx83pdwymdj8np6v9gdjrgdjd3m7l463j0nzyzz7nf8d99cfgjm71xvsAwAd18qr838g2Alzcl8vmpc01trj64h3mvf543h9crqygs81svzAqlhjhkwxt2b0lj9b1fv372cw65j1v848Alrdkf606A488njv3zq/2

**Comment by tiansh** [comment]
脚本默认不会隐藏这条微博。请按照如下步骤检查一下你的过滤规则：

1. 检查一下截图的两个页面网址是否完全一样；
2. 打开脚本设置“关于脚本 - 调试 - 在控制台打印调试信息”，并刷新页面；刷新后打开浏览器控制台，看看控制台里面有没有关于这条微博被隐藏掉的信息
3. 如果还是没解决的话，方便的话把脚本的设置导出之后给我，我可以再复查一下。设置如果不想传到 GitHub 这可以私信[我](https://weibo.com/yawfscript)。

**Comment by ShimotsukiH** [comment]
今天发现问题能重现
1.  一致  输入连接都是 https://weibo.com/cnocg 加载完成后变成 https://weibo.com/cnocg?is_all=1
2. 不是很懂这个操作 
![image](https://user-images.githubusercontent.com/33424662/48253416-271d3480-e442-11e8-9e23-4bbf216d06c4.png)
今天发现被屏蔽的微博是这个：https://weibo.com/2592843922/H1HbKaia2?from=page_1005052592843922_profile&wvr=6&mod=weibotime&type=comment#_rnd1541754609452
![image](https://user-images.githubusercontent.com/33424662/48253495-5a5fc380-e442-11e8-9460-bb00a9935c06.png)
感觉和“已编辑”这个状态有关？
3. 微博的web版本私信界面不懂怎么发文文件……我这边发吧
[yawf-config.zip](https://github.com/tiansh/yawf/files/2565256/yawf-config.zip)

**Comment by tiansh** [comment]
你在设置里面开了隐藏“篇幅过长需要展开全文的微博”的功能，关掉就好了……
