### ISSUE TITLE
原生视频播放器无法使用

### ISSUE THREAD

**Issue by rimoro** [tiansh/yawf#116]
当使用了浏览器的新功能:  原生视频浏览器时, 微博的视频就停止加载和播放了
![Uploading image.png…]()

**Comment by tiansh** [comment]
图片传失败了。
如果不打开这个功能能正常播放，打开之后就什么视频都不能放了吗？有显示什么出错信息吗？开了缩小图片尺寸的功能吗？

**Comment by leung44** [comment]
不能播放加一，好像是要用Https

![image](//wx4.sinaimg.cn//006VbLRJgy1fy1doa0jzkj30i706xgno.jpg)

**Comment by leung44** [comment]
![snipaste_2018-12-10_09-09-08](https://user-images.githubusercontent.com/30283855/49705752-9e213500-fc5b-11e8-9fc7-c84c1876ca28.jpg)

**Comment by tiansh** [comment]
是所有视频都这样吗？我是直接拿的他给的视频地址，没做什么转换。你看看那个视频的网址如果手动改成 HTTPS 能正常播放吗，能的话我强制改一下协议？

**Comment by leung44** [comment]
> 是所有视频都这样吗？我是直接拿的他给的视频地址，没做什么转换。你看看那个视频的网址如果手动改成 HTTPS 能正常播放吗，能的话我强制改一下协议？

实测我的页面上所有视频都不能播放，手动加个S可以播放

**Comment by tiansh** [comment]
好的，今天晚些时候改一下，把视频都改成 HTTPS 的……

可能是我装了 HTTPS Everywhere 和 NoScript 所以没注意……

**Comment by leung44** [comment]
麻烦你了

**Comment by rimoro** [comment]
![image](https://user-images.githubusercontent.com/38860710/49707766-c44cd200-fc67-11e8-95d6-89e87993ec92.png)
就是这样, 所有的微博视频都是这样, 不能加载不能播放
