### ISSUE TITLE
我的首页微博文章iframe显示

### ISSUE THREAD

**Issue by KIRI-Z** [tiansh/yawf#119]
不知道是feature还是bug，或者设置有误，觉得用起来不是很方便

在「我的首页」timeline上点开微博文章，本应该是在页面内加一个iframe，显示文章内容。
现在的情况是，在当前页面打开微博文章链接。看完文章需要「后退」才能返回timeline
观察下来似乎是先加载了iframe，然后又在当前页面打开了iframe的src

在他人的微博首页上点开文章没有此现象，是以iframe形式打开的。

**Comment by tiansh** [comment]
应该是分组页面和用分组拼凑的首页都会这样？

**Comment by KIRI-Z** [comment]
> 应该是分组页面和用分组拼凑的首页都会这样？

是的，只有在用分组代替首页后才会出现
