### ISSUE TITLE
今天首页不出问题？

### ISSUE THREAD

**Issue by ShimotsukiH** [tiansh/yawf#120]
![image](https://user-images.githubusercontent.com/33424662/50621993-e1ae4c80-0f44-11e9-96c0-3c6061713b31.png)
您好
今天使用微博的时候发现“使用多个分组拼凑首页”功能失灵 首页只显示“xxx”分组已经展示完毕 没看到内容
点进设置页面里面，发现“使用多个分组拼凑首页”里面的分组都变成一个框加一个x
把这些x全删掉打算重新点击分组再设置一遍 就出现如上图那样的情况……

按添加按键也添加不了分组

**Comment by ShimotsukiH** [comment]
![image](https://user-images.githubusercontent.com/33424662/50622293-060b2880-0f47-11e9-85ad-ebbab77e3e63.png)
汇报一下……吧cookie删了重新登陆后毛貌似可以了 就是开头这些地方没有像以前那样自己消息掉

**Comment by tiansh** [comment]
所以只是因为之前登录失效了，再登录一下就好了？
但是登录失效你是怎么打开首页的……

**Comment by ShimotsukiH** [comment]
所以我都唔知发生咩事。😂
就当新浪抽风了。
