### ISSUE TITLE
关于微博视频使用浏览器原生视频播放器

### ISSUE THREAD

**Issue by jeremy1991310** [tiansh/yawf#121]
原生播放器这个想法很好，比微博本身那个播放器要快速简约很多。
唯一有一点问题就是没有音量控制，有的时候声音很大很小很尴尬，还要去调系统音量。
所以我在想，能不能加个选项调用国内CDN提供的video.min.js来播放视频，
比如
https://www.bootcdn.cn/video.js/

**Comment by tiansh** [comment]
不考虑引第三方库。如果你的播放器没有音量控制，你应该考虑换个浏览器。

**Comment by tiansh** [comment]
https://weibo.com/5601033111/H6DajvnOH
