### ISSUE TITLE
不开启“查看图片添加“查看原图”链接打开 ”功能会导致“查看图片添加“打包下载”链接（试验性） ”无效

### ISSUE THREAD

**Issue by fireattack** [tiansh/yawf#122]
如题，如果设置成这样：

![image](https://user-images.githubusercontent.com/4130991/50937883-5567c200-143b-11e9-8541-d80ac8a884eb.png)

那么点击“打包下载”按钮只会打开当前图片的大图。

有趣的是，如果也勾选下面的“点击略缩图直接开始下载”，则可以通过点击略缩图下载tar。

**Comment by tiansh** [comment]
感谢反馈。应该是因为插入“打包下载”那个按钮的时候要考虑“查看原图”按钮的位置，所以出问题了。有空修一下。你要么暂时先把查看原图打开……

**Comment by fireattack** [comment]
没问题，take your time.
