### ISSUE TITLE
进入微博搜索页面后导航栏图标出错+搜索页视频会自动播放

### ISSUE THREAD

**Issue by tuanzi0630** [tiansh/yawf#123]
![qp6 dd0tm2 8aq2c2ppt e](https://user-images.githubusercontent.com/42299911/52143951-ce071a80-2697-11e9-96d7-538698f4a5d5.png)
![x a3uf l l pnugtdzw4](https://user-images.githubusercontent.com/42299911/52143957-d0697480-2697-11e9-9a08-89fc032ee474.png)

**Comment by tuanzi0630** [comment]
![d kz1 5 svzt_n u9riiz5](https://user-images.githubusercontent.com/42299911/52144045-145c7980-2698-11e9-95be-2ab180966567.png)

**Comment by tiansh** [comment]
导航栏应该是微博自己的问题。脚本很多功能也不打算支持搜索页。你要是真的需要经常用搜索的话，建议你用这个地址：https://www.weibo.com/tsh90/home?is_search=1&key_word=微博搜索&gid=-42

**Comment by tiansh** [comment]
搜索页面和别的页面差别太大，目前没打算处理视频的问题。
