### ISSUE TITLE
微博每次进入首页版面格式不对

### ISSUE THREAD

**Issue by hxg1683** [tiansh/yawf#125]
如图所示
![image](https://user-images.githubusercontent.com/17562077/52833076-33d2b800-3116-11e9-9daf-8de55c324a58.png)
多次刷新之后才会变正常， 请问这是什么原因导致呢？谢谢。

**Comment by tiansh** [comment]
这就是 CSS 没加载好吧，感觉你不开脚本也不会有什么差别？

**Comment by hxg1683** [comment]
> 这就是 CSS 没加载好吧，感觉你不开脚本也不会有什么差别？

关掉脚本再打开微博，并没有出现类似的问题。可能就是个人电脑出现的问题吧，那就不管它了吧，谢谢。
