### ISSUE TITLE
主页还没有滚动到显示区域的视频有时候会自动播放

### ISSUE THREAD

**Issue by Sunev** [tiansh/yawf#128]
蛮惊悚的，就是微博主页打开之后，预加载的但是还没有滚动到窗口的视频
在什么都没做的情况下自己播放了。。我没找到重现方法，感觉挺随机的，一周总有两三次吧

因为不在可见区域，稍微滚一下鼠标滚轮，就会停止播放

能不能给视频的播放event做一个console.trace看看是怎么回事？

**Comment by tiansh** [comment]
开了使用原生播放器的功能吗？

**Comment by Sunev** [comment]
没有的

**Comment by Sunev** [comment]
导出的配置文件，供参考
[yawf-config.zip](https://github.com/tiansh/yawf/files/2926664/yawf-config.zip)

**Comment by tiansh** [comment]
如果没开这功能，这问题应该是微博自己的问题。如果开这功能能解决的话那建议打开这功能。你试试，如果打开这功能还是没用的话我再处理。

**Comment by vault101** [comment]
> 如果没开这功能，这问题应该是微博自己的问题。如果开这功能能解决的话那建议打开这功能。你试试，如果打开这功能还是没用的话我再处理。

打开后，视频不可见时能否支持自动停止播放呢？

**Comment by tiansh** [comment]
还有问题再说，我这打开这个功能之后，目前没法复现。先关掉了。
