### ISSUE TITLE
关于【隐藏模块 - 标识/图标】的一个小的建议

### ISSUE THREAD

**Issue by AnnAngela** [tiansh/yawf#130]
由于微博移除了部分标识/图标的 background-position 导致在【隐藏模块 - 标识/图标】中看不见部分图标，希望能在脚本内添加相关的 background-position 并注明已被移除。如果很麻烦或者不知道对应的 background-position 的话可以直接关闭这个 issue 的_(:зゝ∠)_
![image](https://user-images.githubusercontent.com/9762652/55845324-fb7ab380-5b73-11e9-9ef4-0f8dd57aa807.png)

**Comment by tiansh** [comment]
扩展版已经把后面那些合并成一个更多了，脚本版后面会跟着这么干……

**Comment by tiansh** [comment]
<img width="607" alt="药方 版面清理 设置" src="https://user-images.githubusercontent.com/6500326/55857774-5d0d4300-5bb1-11e9-8bc1-50400cd8be7e.PNG">

当时写扩展版的时候这功能还没出问题，我也就没改，没料到这么快就出问题了……
其实是他们的图标位置不够用了……

**Comment by AnnAngela** [comment]
扩展版有chrome的吗，似乎没有的样子

**Comment by tiansh** [comment]
没有，目前没打算做 Chrome 版，脚本版还会继续更。

**Comment by AnnAngela** [comment]
好的，感谢作者大大

**Comment by tiansh** [comment]
已经改好了。之前忘记关了，关掉……
