### ISSUE TITLE
建议：希望能够提供自动检测自己发布的微博被屏蔽的功能

### ISSUE THREAD

**Issue by tangtt8** [tiansh/yawf#132]
因为新浪总是有这样那样的敏感词，这种偷偷摸摸的屏蔽并没有任何提示，自己难以发现
特征是阅读数极低，因为只有自己能看到，所以刷新自己的微博几次就只有几次阅读
希望可以弄一个提示近期发布的某条微博阅读数异常低的功能吧

**Comment by tiansh** [comment]
被渣浪屏蔽的表现包括：
1. 别人在首页/分组页上刷不到这条消息，只能点到作者的个人页看全部微博才能看到；
2. 这条微博不会出现在搜索或者话题里面；
3. 由于上面两点，微博的阅读数量会很少，阅读数量包括你自己看的次数以及其他人点到你的主页看到的数量

这功能比较麻烦的地方在于：
1. 如果通过阅读量来判断，很难判断多少是多，多少是少。对于一个有1000活跃粉丝的博主来说，如果在白天发布一小时后阅读数量没100，那么基本上可以判断是被屏蔽了。但是如果是一个有10粉丝的博主，基本上没被屏蔽的微博，一周后也难得有100的阅读量。
2. 如果通过搜索来判断，一个是很难抽取搜索用的文本，另一个是如果文字量较少，恐怕搜索不是什么好办法（搜索请用  weibo.com/home?is_search=1&key_word={关键词} ，这样搜到的是自己和关注的人的，不是所有人的，但是效果是一样的 ）
3. 如果用其他账号的话需要有另外一个帐号来登录，用来检测别的博主是不是有微博被屏蔽了还好，用来检测自己的就不是很方便

除了实现上的问题外，我其实也不是太清楚这功能应该做成什么样：
1. 什么时候去检查？只要开着微博每过一段时间查一次？
2. 发现问题的话怎么办？

**Comment by tangtt8** [comment]
我觉得比较现实的还是通过阅读数判断，至于阅读数的阈值可以交给用户自行设置，而且这种微博阅读数过20都很难（另外被偷偷屏蔽的微博，其中一部分博主自己是可以搜索到的）
检测时机就是在主人访问自己主页的时候自动扫一遍，或者每天扫一遍主页，大部分博主每天的发博量应该都不会超过一屏吧，我现在都是隔段时间到主页看一看
发现问题就像关注变化一样提醒一次，然后博主自行去处理就行了吧

**Comment by tiansh** [comment]
添加了一个在个人主页高亮显示阅读数少于某个阈值的微博的功能，你可以试试。
