### ISSUE TITLE
“恢复图片大小为正常尺寸”功能显示异常

### ISSUE THREAD

**Issue by VonXXGhost** [tiansh/yawf#133]
开启前的正常显示效果：
![snipaste_20190613_165447.jpg](https://i.loli.net/2019/06/13/5d020fac70e7362290.jpg)
开启后图片的比例和显示区域会产生异常：
![snipaste_20190613_165422.jpg](https://i.loli.net/2019/06/13/5d020fe3459f839885.jpg)
此问题大概从几天前开始出现

**Comment by tiansh** [comment]
好的，知道了，在做了。（×

**Comment by tiansh** [comment]
应该好了，<s>短发林克应该不会被压扁了</s>。
