### ISSUE TITLE
设置最新的微博为首页会刷新两次

### ISSUE THREAD

**Issue by cgq355716727** [tiansh/yawf#135]
钩选 使用最新微博代替首页（微博按发布时间排列）（推荐）
首页会刷新两次

**Comment by tiansh** [comment]
我这会刷新一次，因为要从默认的首页跳转到这个按时间排列的页面 https://weibo.com/home?wvr=5&is_new=1 ，如果你是通过浏览器书签访问微博的，可以把书签改成这个跳转后的网址。我不太确定你那里刷新两次是怎么回事……

**Comment by luxiyourbro** [comment]
> 我这会刷新一次，因为要从默认的首页跳转到这个按时间排列的页面 https://weibo.com/home?wvr=5&is_new=1 ，如果你是通过浏览器书签访问微博的，可以把书签改成这个跳转后的网址。我不太确定你那里刷新两次是怎么回事……

我也是，从地址栏输入“w”，chrome自动识别出微博网站，然后回车后首页刷新一次

**Comment by tiansh** [comment]
如果你开了使用“最新微博”/“分组”/“多分组”代替首页的功能，那么就是会跳转一次。
