### ISSUE TITLE
双#内容中的关键词不会被屏蔽

### ISSUE THREAD

**Issue by luxiyourbro** [tiansh/yawf#137]
![image](https://user-images.githubusercontent.com/32382388/62843836-9ab0e280-bcef-11e9-96c4-c207bf445d52.png)

**Comment by tiansh** [comment]
试试 tiansh.github.io/yawf4
或者在下面找到哪些识别为内容的设置，不过这个设置马上就要被砍掉了。

**Comment by luxiyourbro** [comment]
这个问题出现的概率很少，双#比较少，无关紧要

**Comment by tiansh** [comment]
现在 4.0 已经会被识别到了
