### ISSUE TITLE
连续三个“哆啦A梦吃惊”的表情会导致微博显示不正常

### ISSUE THREAD

**Issue by Nidhoggur1993** [tiansh/yawf#138]
如题，关闭药方后显示正常，
转发框内会把内容显示为如下形式

> //@ USERA: img class="W_img_face" render="ext" src="data:image/svg+xml," title="[哆啦A梦吃惊]" alt="[哆啦A梦吃惊]" type="face" ori-src="https://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f0/dorachijing_org.gif" yawf-ori-src="https://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f0/dorachijing_org.gif" yawf-pause-animate="yawf-pause-animate" style="visibility: visible;"img class="W_img_face" render="ext" src="data:image/svg+xml," title="[哆啦A梦吃惊]" alt="[哆啦A梦吃惊]" type="face" ori-src="https://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f0/dorachijing_org.gif" yawf-ori-src="https://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f0/dorachijing_org.gif" yawf-pause-animate="yawf-pause-animate" style="visibility: visible;"img class="W_img_face" render="ext" src="data:image/svg+xml," title="[哆啦A梦吃惊]" alt="[哆啦A梦吃惊]" type="face" ori-src="https://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f0/dorachijing_org.gif" yawf-ori-src="https://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f0/dorachijing_org.gif" yawf-pause-animate="yawf-pause-animate" style="visibility: visible;"//@ USERB:转发微博

药方设置见附件
[-药方设置-20190826.txt](https://github.com/tiansh/yawf/files/3539892/-.-20190826.txt)

**Comment by tiansh** [comment]
你用的是不是 TM？临时解决方案是把 TM 设置的 XHR 安全 的 用户域名白名单 里面加一个 *

这大概是
1. 一个 TM 的不知道什么鬼 bug
2. 一个微博的过滤bug
3. 你开了暂停动画功能
导致的

**Comment by Nidhoggur1993** [comment]
关掉暂停动画的功能之后就好了，感谢
![image](https://user-images.githubusercontent.com/12947582/63819068-6cc9d000-c976-11e9-817e-1d19a2e03444.png)

（我反应了好久才理解TM=油猴）

**Comment by tiansh** [comment]
TM 是 Tampermonkey，油猴是 Greasemonkey。
