### ISSUE TITLE
新版设置中“查看原图”选项中没有了添加广告过滤规则提示

### ISSUE THREAD

**Issue by loyle5** [tiansh/yawf#139]
新版设置中“查看原图”选项中没有了添加广告过滤规则提示
导致现在不知道咋添加规则了

**Comment by tiansh** [comment]
因为这个问题在扩展版里面不存在（扩展版权限足够，不会出现这个问题），所以做扩展版的时候没加。脚本版是扩展版打包出来的，所以也跟着没有……

暂时可以参考[这句话](https://github.com/tiansh/yawf/blob/0ca9dfe8d238d5961085417f6c23d6bbd6e9da75/Yet_Another_Weibo_Filter.user.js#L820)

> 选择打开包含原图的网页时，脚本会生成一个一次性的查看当前图片的网页。如果您启用了各类广告屏蔽插件，该页面可能会被误杀拦截。对于兼容 EasyList 的广告屏蔽插件，请在白名单中添加 <code>@@|blob:https://weibo.com$popup</code> 和 <code>@@|blob:https://d.weibo.com$popup</code> 以允许该弹窗。

**Comment by loyle5** [comment]
好的 之前没找到这句在哪 解决了 感谢作者
