### ISSUE TITLE
[可能是BUG？]查看微博编辑历史时会被Sina Visitor System阻止接收结果

### ISSUE THREAD

**Issue by AnnAngela** [tiansh/yawf#141]
查看微博编辑历史时，`feedHistoryPage`函数会构造一个链接来获取历史信息，该函数默认该链接返回结果必定是json，于是用了`const resp = await network.fetchJson(url + '');`，结果不知道为什么，在fetch的时候会被新浪跳转到`https://passport.weibo.com/visitor/visitor?entry=miniblog blablablabla`导致`JSON.parse`报错，如下图所示
![image](https://user-images.githubusercontent.com/9762652/64910005-fd5d2a00-d744-11e9-9c4f-4f5d02003754.png)
希望能得到修复

**Comment by tiansh** [comment]
你是怎么在 Edge 上安装了暴力猴的，我这找不到。

**Comment by AnnAngela** [comment]
1. [欢迎试用Microsoft Edge Insider](https://www.microsoftedgeinsider.com/zh-cn/)；
2. 后者.jpg。

**Comment by tiansh** [comment]
我这复现不出来这个问题……

**Comment by AnnAngela** [comment]
![image](https://user-images.githubusercontent.com/9762652/65304066-47fdfc80-dbb2-11e9-9a1c-a2896c9641d7.png)
没开代理，首页仍然这样

**Comment by tiansh** [comment]
试试新建一个全新的配置文件只装ViolentMonkey？至少先排除一下是不是其他扩展的干扰？

**Comment by AnnAngela** [comment]
![image](https://user-images.githubusercontent.com/9762652/65305966-f015c480-dbb6-11e9-8cf3-e0f7098cf6df.png)
只装暴力猴依旧如此

**Comment by tiansh** [comment]
对了，你的浏览器有没有做任何特殊的设置？

**Comment by AnnAngela** [comment]
> 对了，你的浏览器有没有做任何特殊的设置？

没有，我试过在Windows Sandbox里依然如此

**Comment by tiansh** [comment]
复现不了，换了一台机器，因为这机器没配置上网工具，所以是直接从 GitHub 上下载了 VM 的代码（851b58ce60c6dcf7dd242de534f6eb4bd46a7fd3）编译之后用开发模式装上去的。浏览器版本是 Version 78.0.276.14 (Official build) beta (64-bit)。

<img width="778" alt="yawf-edited" src="https://user-images.githubusercontent.com/6500326/66539061-93347b00-eb72-11e9-8d17-2f2be5c51abe.png">

**Comment by tiansh** [comment]
Edge 出了正式版。我这依旧复现不了：

<img width="782" alt="查看编辑记录" src="https://user-images.githubusercontent.com/6500326/72510404-49c68c80-3841-11ea-9943-b47a5d63b14a.PNG">

你那现在还有这问题吗？

**Comment by AnnAngela** [comment]
有的时候有有的时候没有，应该是网络问题了，不管了_(:зゝ∠)_
