### ISSUE TITLE
微博搜索页面内容会被yawf-dialog-outer遮住

### ISSUE THREAD

**Issue by eaudouce** [tiansh/yawf#142]
https://s.weibo.com/weibo?q=%23%E5%85%B7%E6%83%A0%E5%96%84%E5%AE%89%E5%AE%B0%E8%B4%A4%E6%8F%90%E4%BA%A4%E7%A6%BB%E5%A9%9A%E8%AF%89%E8%AE%BC%23&from=trendtop_api&refer=index_hot_new

**Comment by tiansh** [comment]
可以给个截图吗？我这看着挺正常的

**Comment by tiansh** [comment]
以及说一下自己的运行环境（浏览器、猴子的名字，以及他们的版本）。

**Comment by tiansh** [comment]
偶然发现关注列表有变化的时候会有这个问题，确认关注列表变化之后就没了。不确定是不是你反馈的问题。

**Comment by eaudouce** [comment]
不好意思，没注意到github消息。
更新版本之后就好了，不记得当时关注列表有没有变化了。
因为无法重现，不能截图。大概情况就是除了顶部通栏，其他部分都被半透明的灰色遮住了。
F12看发现是被.yawf-dialog-outer遮住，就给.yawf-dialog-outer加了display:none，能正常用。
后来有版本自动更新，这个问题就没重现过。

**Comment by XinSSS** [comment]
![iShot2020-05-1810 21 44](https://user-images.githubusercontent.com/30732527/82168471-6bb84480-98f1-11ea-9abd-bfe79c0d78f0.png)
我这里出现了....

**Comment by XinSSS** [comment]
![iShot2020-05-1810 23 20](https://user-images.githubusercontent.com/30732527/82168626-bdf96580-98f1-11ea-81f3-e2155f3403ff.png)
![iShot2020-05-1810 23 11](https://user-images.githubusercontent.com/30732527/82168629-bf2a9280-98f1-11ea-9d51-58ccf38359c6.png)

**Comment by tiansh** [comment]
翻到网页最下面，能看到什么脚本插入的额外内容吗

**Comment by XinSSS** [comment]
@tiansh 
![iShot2020-05-1810 27 52](https://user-images.githubusercontent.com/30732527/82168864-5f80b700-98f2-11ea-8cce-1a141e778f05.png)
[微博搜索.zip](https://github.com/tiansh/yawf/files/4641699/default.zip)

**Comment by tiansh** [comment]
很好，这次是更新提示……
总之问题是更新提示不应该出现在搜索页面……

**Comment by XinSSS** [comment]
> 很好，这次是更新提示……
> 总之问题是更新提示不应该出现在搜索页面……

了解了...我是Chrome地址栏搜索引擎直达的...所以...
