### ISSUE TITLE
微博头条自动跳转问题

### ISSUE THREAD

**Issue by zxyacb** [tiansh/yawf#143]
在个人主页点头条文章，头条文章显示几秒钟后会自动转到头条的独立显示页面，网址是https://weibo.com/ttarticle/p/show?id=xxxx，没有关闭按钮，只能通过历史后退回原来的页面，
在其它人微博主页的头条文章会正常显示，即弹出一个框显示文章，可以正常关闭。

**Comment by tiansh** [comment]
应该是分组页面、最新微博页面都这样。而且你开不开脚本都这效果吧。

**Comment by zxyacb** [comment]
最近试出来的，火狐新开配置文件试了，微博过滤-首页-勾选 使用单个分组页代替首页，打开头条文章就会出现页面跳转，不勾选正常的弹框显示

**Comment by tiansh** [comment]
那就不是脚本的问题，因为那个页面你不开脚本也那样。
