### ISSUE TITLE
建议增加视频下载功能

### ISSUE THREAD

**Issue by zhengruiw02** [tiansh/yawf#144]
首先非常感谢作者制作的这个脚本，本人一直在使用。
我建议给微博内的视频，增加一个下载小按钮，可以直接把mp4格式的视频下载下来。参考SaveFrom.net helper这个在facebook就有类似功能。谢谢！

**Comment by tiansh** [comment]
用原生视频播放器之后可以右键下载。

**Comment by zhengruiw02** [comment]
> 用原生视频播放器之后可以右键下载。

打开使用原生播放器，可以在播放器菜单里下载了，非常感谢
