### ISSUE TITLE
更新一次关注列表要花很久的时间

### ISSUE THREAD

**Issue by Konano** [tiansh/yawf#145]
原因未知……
![image](https://user-images.githubusercontent.com/22500116/77496588-43c6da80-6e86-11ea-938d-b6bfdb58a8a2.png)

**Comment by tiansh** [comment]
你给关了是他好了还是怎么回事？

**Comment by Konano** [comment]
> 你给关了是他好了还是怎么回事？

对，好像又好了，等再次出现问题的时候我再重开（莫名其妙就好了

**Comment by tiansh** [comment]
那这次有提示任何更新变化吗？

**Comment by Konano** [comment]
有，就挺正常的

**Comment by Konano** [comment]
同样的事情又发生了
![image](https://user-images.githubusercontent.com/22500116/80942691-fe4be480-8e17-11ea-87d3-08debb162310.png)

**Comment by tiansh** [comment]
我没看到现场我也不知道是怎么回事啊。或者有人pr，或者有人告诉我详细情况，或者我哪天自己遇到。在这之前应该是不会有任何修复的。。。

**Comment by Konano** [comment]
我不太清楚具体 debug 是怎么 debug 法，调试信息看不懂。
调试信息有帮助吗？有的话我可以贴上来。

**Comment by Sunev** [comment]
在“正在更新”的旁边加一个计数器（111/233）之类的，可以比较直观的观察进度，或许会有比较大的体验改善。
比较有可能单纯是关注列表太大了吧。

**Comment by tiansh** [comment]
> 在“正在更新”的旁边加一个计数器（111/233）之类的，可以比较直观的观察进度，或许会有比较大的体验改善。

加个计数器可以有……大概

**Comment by tiansh** [comment]
新版在正在更新后面添加了一些提示文字，表示正在更新的进度。你可以更新试试。看看他报告的是在哪一步出错了。。。

**Comment by Konano** [comment]
![image](https://user-images.githubusercontent.com/22500116/82135225-cd65a980-9832-11ea-9204-94e30237e58b.png)
【数据获取出错】

**Comment by tiansh** [comment]
呣呣呣呣呣呣……
可以的话打开调试输出（关于脚本选项卡），然后刷新页面。等出现这个的时候，看一下“Fetch Follow: fetching following failed”上一行出错的内容是什么。

还有把关注列表的第二页，网页另存为之后发给我，我看看……

**Comment by Konano** [comment]
![image](https://user-images.githubusercontent.com/22500116/82184640-8ce15b00-991a-11ea-9d89-44941a0d62a4.png)
全过程

**Comment by tiansh** [comment]
可以的话，打开你这截图里面那个 fetch url 后面的那个 url，把那个网页另存为之后私信给我。应该是因为无法解析你那个页面里面的数据导致的。为什么无法解析我也不知道。

**Comment by tiansh** [comment]
等等， open.weibo.com 这个域名是什么？

**Comment by Konano** [comment]
唔……貌似是第一次爬的时候获得了错误的地址（指 open.weibo.com）

**Comment by tiansh** [comment]
我这打开脚本的情况下根本没法正常打开这个域名。你那里正常吗……

**Comment by tiansh** [comment]
总之我先把 open.weibo.com 网址从脚本里面排除了……

**Comment by Konano** [comment]
我也没法打开这域名，而且在经过一次正常更新后就又好了。
我觉得下次得监控下为什么会出现 open.weibo.com……

**Comment by tiansh** [comment]
应该是在那个页面触发了自动更新。所以用了那个域名……

**Comment by Sunev** [comment]
open.weibo.com是微博的开发者平台，api调用之类的都在上边
