### ISSUE TITLE
插件很好用的,这两个功能可以有!

### ISSUE THREAD

**Issue by Aoiyy** [tiansh/yawf#146]
1.在浏览微博用户相册图片时,可以添加一个收藏按钮吗?
2.增强微博页面的收藏功能。点收藏的同时会把微博保存至本人的印象笔记(Evernote)中

**Comment by tiansh** [comment]
相片本来也没有收藏功能啊？

印象笔记的功能去找印象笔记，Evernote 的功能区找 Evernote，都不要来找我。
