### ISSUE TITLE
无法设置

### ISSUE THREAD

**Issue by pwelyn** [tiansh/yawf#148]
![Xnip2020-04-14_16-39-45.png](https://img01.sogoucdn.com/app/a/100520146/c83af5c0764aefb1c1def9b5bff3470f)

所有设置选项只有文字没有别的

**Comment by pwelyn** [comment]
macOS 
Chrome

**Comment by tiansh** [comment]
你好，你的图片我打不开。具体发生了什么问题？

**Comment by pwelyn** [comment]
> 你好，你的图片我打不开。具体发生了什么问题？

找到原因了，是因为我使用的是AdGuard安装的插件，所以在微博里面不能设置，我使用油猴安装就可以正常使用了，谢谢
