### ISSUE TITLE
失效了？？？

### ISSUE THREAD

**Issue by WQWDIHI** [tiansh/yawf#153]
不知道是不是微博更新了，突然不能用了

**Comment by tiansh** [comment]
我这正常！！！

**Comment by WQWDIHI** [comment]
好吧，我自己排查




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "田生"<notifications@github.com&gt;; 
发送时间: 2020年7月25日(星期六) 晚上10:17
收件人: "tiansh/yawf"<yawf@noreply.github.com&gt;; 
抄送: "￥endetta&apos;=&apos;=&apos;"<1343534677@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tiansh/yawf] 失效了？？？ (#153)





 
我这正常！！！
 
&mdash;

**Comment by WQWDIHI** [comment]
我就开一个脚本也无法生效
&nbsp;我浏览器是百分 内核是80，我用了好久了就上周开始不能用的很奇怪，退号重登有效但是刷新之后就又没了，我是不懂啥原因了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "田生"<notifications@github.com&gt;; 
发送时间: 2020年7月25日(星期六) 晚上10:17
收件人: "tiansh/yawf"<yawf@noreply.github.com&gt;; 
抄送: "￥endetta&apos;=&apos;=&apos;"<1343534677@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tiansh/yawf] 失效了？？？ (#153)





 
我这正常！！！
 
&mdash;
