### ISSUE TITLE
考虑排除 passport.weibo.com

### ISSUE THREAD

**Issue by zhmars** [tiansh/yawf#154]
登录验证页面，启用后会导致无法正确显示

![2020-08-08 18-09-38屏幕截图](https://user-images.githubusercontent.com/18466397/89707625-86570280-d9a2-11ea-8d67-2b7a53dc26b1.png)

**Comment by tiansh** [comment]
已更新。

**Comment by tiansh** [comment]
另外可以试试从 login.sina.com.cn 登录
