### ISSUE TITLE
找不到漏斗图标

### ISSUE THREAD

**Issue by NewCockCity** [tiansh/yawf#158]
![image](https://user-images.githubusercontent.com/71121712/92888646-1677e400-f448-11ea-898b-738128c34ff6.png)
![image](https://user-images.githubusercontent.com/71121712/92888761-2f809500-f448-11ea-988f-d21a0476ad47.png)
大佬，如图tampermonkey已经在运行药方了，但是找不到漏斗图标，不知道该怎样进行设置。（药方为4.0.82版，禁用其它所有插件也是这样，浏览器为edge chromium正式版85.0.564.51版）

**Comment by tiansh** [comment]
没登录没有。

**Comment by NewCockCity** [comment]
原来是这样，感谢解答
