### ISSUE TITLE
yawf会自动把t.cn整个页面完全屏蔽掉

### ISSUE THREAD

**Issue by Tzwcard** [tiansh/yawf#159]
突然发现t.cn整个被display: none了
排查了一下是暴力猴里面的YAWF脚本导致的
![image](https://user-images.githubusercontent.com/12098388/93233991-50c9e400-f7ae-11ea-9eac-522826edc24b.png)
![image](https://user-images.githubusercontent.com/12098388/93234021-5c1d0f80-f7ae-11ea-9d97-b41f8809dff5.png)

**Comment by tiansh** [comment]
报错信息说的啥？

**Comment by Tzwcard** [comment]
![image](https://user-images.githubusercontent.com/12098388/93438685-39027500-f900-11ea-8931-8ddb25f5cbb9.png)

**Comment by tiansh** [comment]
更新稍微处理了一下，因为之前我这也无法复现，所以我也不知道能不能用，你更新后再试试？

**Comment by Tzwcard** [comment]
更新之后没问题 可以正常看到链接了
因为现在不知道是不是我这边的原因t.cn不会自己跳转 之前每次访问都直接空白掉无法查看长链接

![image](https://user-images.githubusercontent.com/12098388/93724002-ff6a8c00-fbd5-11ea-8a3a-aab52f265eeb.png)
虽然还会提示uncaugh error就是了

**Comment by tiansh** [comment]
脚本有一个长链接自动跳转的功能，需要的话可以打开。这个错误信息是正常情况，不用担心。
