### ISSUE TITLE
Not work in Weibo V7 at Safari

### ISSUE THREAD

**Issue by EXSERENS** [tiansh/yawf#161]

**Comment by tiansh** [comment]
Safari is not targeted browser of this script. And I will not work on this as I don't have access to a Safari browser at all. PR's are still welcomed.

**Comment by tiansh** [comment]
Btw, incase anyone want to contribute. Codes marked in `region yaofang://` are maintained in project https://github.com/tiansh/yaofang and any modify should be worked on that repo.
