### ISSUE TITLE
[功能请求] 过滤带认证用户标记的微博内容

### ISSUE THREAD

**Issue by XHXIAIEIN** [tiansh/yawf#168]
**过滤选项**
- 普通用户 (无标记)
- 个人认证用户(红V、金V、)
- 企业认证用户(蓝V)

开启功能后，可以只显示、屏蔽显示特定认证用户的微博内容。

**使用场景**： 
开启过滤后，页面上只显示带有 `蓝标` 企业认证用户的微博内容。 
例如有时候想搜索某个话题下企业号发布的东西，但是不太好找。 
  
看了一下目前现有的内容关键词过滤、作者过滤、话题过滤....似乎都是目的性很强的过滤规则，只有清楚的知道要屏蔽谁才能生效。

**Comment by tiansh** [comment]
正则过滤时过滤的原文是带用户标记的，关键词过滤时不带。可以在关于脚本那里打开调试和正则过滤规则的调试，看一下控制台，然后根据那个设置。

**Comment by tiansh** [comment]
正则过滤的格式大概是

```text
@username张三 https://weibo.com/u/1012345678 [微博个人认证]\u2028太好了~\u2028Android客户端\u20282021-03-08T00:00:00.000+0800
```

**Comment by XHXIAIEIN** [comment]
在搜索页面，控制台输出日志里好像没有包含用户标记的文本，我看到的文本信息是这样的： 

```
""央视新闻\u2028【这份祝福，请查收！#张桂梅祝所有姐妹身体健康更漂亮#】#今天妇女节#，张桂梅在#两会你我他#节目中说：“祝所有的姐妹们身体健康，越来越漂亮。”她还说，作为女子高中的校长，希望能把女孩们培养成“有文化、有道德、有能力，能自尊、自强、自立的人”↓转发分享，祝福每一个“她”！L央视新闻的微博视频\u2028微博云剪\u20285分钟前 转赞人数超过900""
```

""北京海淀法院\u2028#妇女节##女性的力量值得被看见#【海法巾帼风采】唐盈盈——我热爱工作，也热爱生活。音乐、舞蹈带给我快乐，让我的生活丰富多彩。 ​\u2028微博 weibo.com\u202816秒前""
```

---

小声BB：  
当我回到V6的时候才看到了原来微博是有高级搜索功能的，可以搜索认证用户。

**Comment by tiansh** [comment]
搜索页面（包括话题）支持有限……就……
