### ISSUE TITLE
V7版微博信息流中的广告无法屏蔽

### ISSUE THREAD

**Issue by lychichem** [tiansh/yawf#175]
![image](https://user-images.githubusercontent.com/9316590/122383612-9154c900-cf9d-11eb-8df6-efcf20f87a9c.png)
如图，因为我不懂js，所以从源码层面没法发现什么有用特征，目前能确认的广告微博的特征是都有个”广告“标志，因此试图用了
`weibo.com##div.vue-recycle-scroller__item-view:has(div.wbpro-ad-tag)`这条ublock规则屏蔽，但是这个规则处理不了屏蔽掉广告后留下的时间线中的空白，请求前辈出手解决一下

**Comment by tiansh** [comment]
抱歉，周末都在打游戏没看这里，过两天有空更一下……
因为新版用的是Vue，你要调试的话装个 Vue 的调试插件，在他 Vue 启动设置调试为关闭的时候打个断点把调试打开，就能看到这条微博对应的数据了。没记错的话应该是有一个整数字段，根据数值的不同显示不同的文字标记。

**Comment by tiansh** [comment]
应该已经解决了，更新试试。

**Comment by lychichem** [comment]
确认已处理完毕，感谢前辈
