### ISSUE TITLE
微博页面异常

### ISSUE THREAD

**Issue by freyzh** [tiansh/yawf#180]
![微信截图_20210805130352](https://user-images.githubusercontent.com/88474229/128294198-f3457d6b-629a-4e27-bc29-839509f40cec.png)
![微信截图_20210805130412](https://user-images.githubusercontent.com/88474229/128294202-002c89b1-135d-4430-bac5-98f0ed6b7096.png)
清缓存还是不行

**Comment by tiansh** [comment]
脚本是没办法让你网络连接不正常的。所以如果你看到的错误是“×××已拒绝连接”那说明问题不在脚本上，是你或者服务器的网络配置有问题。这种问题或者去找你的网络服务提供商（电信联通之类你购买网络的公司）或者去找微博客服，找我没什么用。
