### ISSUE TITLE
“woo-box-item” 显示问题

### ISSUE THREAD

**Issue by zzz6839** [tiansh/yawf#211]
推文来自设备出现显示错误。
![image](https://user-images.githubusercontent.com/57741549/230615652-fe564d93-4895-4a87-bf30-cb5bc26ff1c5.png)

**Comment by xiaoxutem** [comment]
同款问题

**Comment by genglongsir** [comment]
我也遇到了，小米手机的就会显示成html

**Comment by Trudepo** [comment]
`// 替换掉原有的来源，保证来源本身有个标签，后续用来做拖拽过滤用
      if (source && source.nodeType !== Node.COMMENT_NODE) {
        const newSourceVNode = h('div', {
          class: [this.$style.source, 'yawf-feed-source-container'],
        }, ['来自 ', h('span', {
          class: ['yawf-feed-source'],
          attrs: { draggable: 'true' },
        }, [this.source || '微博 weibo.com'])]);
        // 修改这个地方
        // insertBefore(sourceBox, newSourceVNode, source);
        sourceBox.insertAdjacentHTML(newSourceVNode, source);
        removeChild(sourceBox, source);
      }`
按照这里修改就可以正常显示了

**Comment by Trudepo** [comment]
```
      // 替换掉原有的来源，保证来源本身有个标签，后续用来做拖拽过滤用
      if (source && source.nodeType !== Node.COMMENT_NODE) {
        const newSourceVNode = h('div', {
          class: [this.$style.source, 'yawf-feed-source-container'],
        }, ['来自 ', h('span', {
          class: ['yawf-feed-source'],
          attrs: { draggable: 'true' },
        }, [this.source || '微博 weibo.com'])]);
        // insertBefore(sourceBox, newSourceVNode, source); <------------ 修改这个地方
        sourceBox.insertAdjacentHTML(newSourceVNode, source); // <------------ 改成这样
        removeChild(sourceBox, source);
      }
```

我修改了这里正常显示了

**Comment by Mr-SnowSakura** [comment]
同款问题

**Comment by Mr-SnowSakura** [comment]
> ```
>       // 替换掉原有的来源，保证来源本身有个标签，后续用来做拖拽过滤用
>       if (source && source.nodeType !== Node.COMMENT_NODE) {
>         const newSourceVNode = h('div', {
>           class: [this.$style.source, 'yawf-feed-source-container'],
>         }, ['来自 ', h('span', {
>           class: ['yawf-feed-source'],
>           attrs: { draggable: 'true' },
>         }, [this.source || '微博 weibo.com'])]);
>         // insertBefore(sourceBox, newSourceVNode, source); <------------ 修改这个地方
>         sourceBox.insertAdjacentHTML(newSourceVNode, source); // <------------ 改成这样
>         removeChild(sourceBox, source);
>       }
> ```
> 
> 我修改了这里正常显示了

赞美dalao
