### ISSUE TITLE
搜索页面没有小漏斗

### ISSUE THREAD

**Issue by JixunMoe** [tiansh/yawf#24]
就是那个设定小漏斗

**Comment by JixunMoe** [comment]
http://s.weibo.com/weibo/fireaway
比如这里（。

**Comment by JixunMoe** [comment]
仔细读了下脚本选项，关 Issue… 抱歉 :3

**Comment by tiansh** [comment]
设计如此。
搜索页面因为和其他页面区别太大，所以不打算提供完整的支持。尤其是比较复杂的设置窗口，想要在搜索界面上正确排版会有很大的改动。你可以在首页和搜索页分别点转发，看看两个对话框差别有多大。而yawf在排版上尽量与网站原有界面风格一致，所以导致要兼容两个页面成本太大。
加上如果只是想屏蔽一个用户也用不着开设置窗口。拖拽或右键（右键仅限火狐）足够应付这问题的。所以就特意在搜索页面去掉了漏斗图标。
现在搜索页上仅有部分样式和过滤微博功能是正常的的。也不打算添加其他的功能支持

**Comment by JixunMoe** [comment]
感谢回应 :3
