### ISSUE TITLE
自动尝试恢复被删除的微博

### ISSUE THREAD

**Issue by JayXon** [tiansh/yawf#25]
可以利用自由微博的这个解密功能https://freeweibo.com/decrypt
虽然不是所有微博都能成功，但是可以一试

**Comment by tiansh** [comment]
类似的网站有哪些？他们在中国大陆可以稳定访问吗？这些网站的用户协议和版权声明是否允许引用他们的资源？

另外，考虑到这个脚本现在的隐私协议有冲突，和其他一些问题，这个功能如果采纳，会实现在单独的脚本中。或许会将设置整合到 yawf 的设置中。

21.01.2015, 17:41, "JayXon" <notifications@github.com>:
> 可以利用自由微博的这个解密功能https://freeweibo.com/decrypt
> 
> 虽然不是所有微博都能成功，但是可以一试
> 
> —
> Reply to this email directly or view it on GitHub.

--

**Comment by tiansh** [comment]
因为不合脚本不会访问外部网站的隐私政策，这个功能不会被加到 YAWF 中，所以这里关闭了此问题。
但仍欢迎继续讨论相关问题，视情况可以将该功能实现到其他的脚本中，或如果有人愿意实现微博上的脚本，我可以提供一些基本的技术上的帮助。

**Comment by JayXon** [comment]
类似的网站还有http://weiboleak.com/ ，不过貌似不能查询
我没有找到任何用户协议之类的声明
我同意，单独做一个脚本来实现是比较好的选择
