### ISSUE TITLE
插件已安装，但是无法启用不是Chrome应用商店的应用

### ISSUE THREAD

**Issue by claireqp** [tiansh/yawf#26]
启用为灰色
![qq 20150924221923](https://cloud.githubusercontent.com/assets/13530604/10075757/2169cb5a-630a-11e5-8dc7-b25c852c0958.png)

**Comment by tiansh** [comment]
这个应该是安装的有问题。

1. 先卸载掉现在安装的版本。
2. 从应用商店安装[Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=zh-CN)
  * 确认浏览器右上角多出来了一个 Tampermonkey 的图标
3. 回到[脚本主页](https://tiansh.github.io/yawf/zh-cn.html)点安装脚本
4. Tampermonkey 会托管安装的流程，使用 Tampermonkey 的安装安装脚本。
5. 刷新微博网页

你应该可以在 Tampermonkey 的设置里面找到脚本，而不是在 Chrome 的扩展页面。

**Comment by claireqp** [comment]
啊谢谢，用tampermonkey装了就好了，-3-！
