### ISSUE TITLE
切换账号以后设置不能保留，非关注帐号不能屏蔽

### ISSUE THREAD

**Issue by Exodus000** [tiansh/yawf#27]
浏览器是Safari，请问是本身不支持这两项功能还是我使用姿势不正确？求教...

**Comment by tiansh** [comment]
第一个问题，屏蔽列表是按帐号分开的，你可能需要分别配置多个帐号的设置。另外，设置的导入和导出功能可能可以帮助你更快地完成分别的配置。但如果是切换到第二个帐号再切换回来，设置应该是还在的，如果是这种情况请再说明一下。

第二个问题，没有正确地按帐号隐藏微博时，请确认：
* 这条微博没有因为满足白名单的要求而被显示。
* 打开的是首页、个人主页、热门页面或搜索页面（需要勾选在搜索页面启用）。
* 关于帐号的三个黑名单：“帐号”负责你关注的人，“原创”转发来源那个人，“提到”负责微博正文中提到的人（包括中间转发的人）；确认一下你使用的是正确的列表。顺便一说，拖拽时会自动识别应该加到哪个名单里面。

如果最后还有问题，你可以再试试用 Tampermonkey ，虽然我对这个感觉不是很靠谱……

**Comment by Exodus000** [comment]
第一个问题里确实是切换到第二个账号再切换回来时原来的设置清空。第二个问题里三个黑名单在点击漏斗图标后打开的页面设置确实有效，但是在
允许拖拽屏蔽的情况下无论拖头像还是用户昵称都没有反应……

**Comment by tiansh** [comment]
估计问题是出在你安装脚本的那个软件上了，你用的 JSBlocker 还是 Tampermonkey 还是什么？换 <a href="http://tampermonkey.net/?browser=safari">Tampermonkey</a> 试试？ // 我现在手头没 Safari ……

**Comment by Exodus000** [comment]
原来用的JSBlocker，换Tampermonkey <http://tampermonkey.net/?browser=safari>
以后拖拽屏蔽无效的问题解决了，换帐号问题还没测试

2015-12-10 23:14 GMT-08:00 田生 <notifications@github.com>:
