### ISSUE TITLE
顶部功能条显示问题

### ISSUE THREAD

**Issue by forestballad** [tiansh/yawf#29]
阅览器：Chrome Version 47.0.2526.111 m
Tampermonkey：v3.12.58
OS：WIN10 英文版
微博界面语言：中文
从如下宽度
![image](https://cloud.githubusercontent.com/assets/6697754/12406572/3ad69d8a-be1c-11e5-8859-fee261c705f5.png)
拉到如下宽度
![image](https://cloud.githubusercontent.com/assets/6697754/12406593/5129d002-be1c-11e5-97ce-412df5dae10f.png)
（即是在搜索框变成较长的版本之后？）
按钮图标等出现在了置顶功能条的下方。
不知道有没有讲的够清楚……

**Comment by tiansh** [comment]
是在大陆地区访问的微博还是其他地区？目测是海外用户？

都开了什么关于导航栏的功能，加了什么自定义样式吗？
“恢复经典导航栏样式”功能开了吗？

**Comment by tiansh** [comment]
能确定问题了：受影响的是分辨率大的海外用户……
原因是导航栏改版，什么时候改的我就不知道了。

**Comment by tiansh** [comment]
应该已经解决了，更新试试。
