### ISSUE TITLE
脚本与“搜索类似图片”的功能冲突

### ISSUE THREAD

**Issue by lychichem** [tiansh/yawf#31]
试图右键点击微博中出现的图片进行图片搜索时，只能弹出此脚本的“创建过滤器”菜单而没有“搜索此图片”的菜单，使用chrome最新稳定版，TM beta版，微博页面最近没有改版过。建议在弹出“创建过滤器”的菜单的语句那里排除img标签

**Comment by tiansh** [comment]
我这里 Chrome 48.0.2564.116 m (64-bit) 没见到浏览器支持右键菜单功能。
你用的具体版本是多少？打开了什么浏览器的设置开关吗？

**Comment by tiansh** [comment]
另一个问题是，图片搜索功能是什么。我这在图片上右键也看不到图片搜索功能。不管脚本是否打开，也不限于微博。

**Comment by lychichem** [comment]
默认搜索引擎设置成谷歌，随便右键一张图片你就知道了，只有在微博弹出的不是正常的右键菜单

**Comment by lychichem** [comment]
![2016-02-21 1](https://cloud.githubusercontent.com/assets/9316590/13201718/5ddd24dc-d8b8-11e5-88b4-c3895c490a26.png)
![2016-02-21 2](https://cloud.githubusercontent.com/assets/9316590/13201719/5efd00b2-d8b8-11e5-870a-c7096e36086a.png)
这是不同页面的效果

**Comment by tiansh** [comment]
检查了一下你说的这个问题。

首先，因为你开启了浏览器试验性功能 chrome://flags/#enable-experimental-web-platform-features ，所以才会看到这个功能。正常情况下的 Chrome 用户，至少在目前 48 版本下，是看不到这个功能的。

第二，脚本不可能在给微博区域提供右键菜单功能的同时排除图片区域。当然如果你觉得有什么好的办法解决这个问题，欢迎 PR 过来。

第三，不确定这个问题是 Chrome / Chromium 的 bug ，还是他们设计如此。但至少这不是 YAWF 脚本的 bug 。你可以试试 [MDN上关于上下文菜单的示例页面](https://mdn.mozillademos.org/en-US/docs/Web/HTML/Global_attributes/contextmenu$samples/ContextMenu_Example) ，页面中有同样的情况。如果你觉得“搜索”等功能的右键菜单项缺失是一个 bug ，你应当检查一下 Chromium 的问题追踪器，并用上面那个示例页面为例子向 Chromium 报告问题。

最后，如果你不希望使用右键菜单设置过滤器，你可以关闭脚本设置“微博过滤 - 脚本 - 使用右键菜单快速创建过滤器”选项，禁用该功能。

另外补充两个不太相关问题：1. 建议只在Chrome的测试版中使用TM的Beta版，否则可能有兼容问题。 2. 你图中那条微博可能是粉条，需要的话可以在“更多 - 隐藏以下微博 - 广告/商品 - 粉丝头条”中隐藏它。

**Comment by lychichem** [comment]
你说的没错，确实是实验性网络平台的功能，我以为那个和quic有关就一直开着，那我关掉好了
