### ISSUE TITLE
包含原图的网页标题乱码

### ISSUE THREAD

**Issue by JayXon** [tiansh/yawf#34]
**问题描述**：

包含原图的网页标题乱码

**相关设置**：

添加“查看原图”链接打开 包含原图的网页
Windows语言和Chrome语言均为英文

**操作步骤**：

查看原图

**期望结果**：

标题无乱码

**实际结果**：

![title](https://cloud.githubusercontent.com/assets/1552641/15104694/f2221118-156f-11e6-9c44-0e72ff3228ad.PNG)

**附加信息**：

**以前的版本有这个问题吗**：从我装这脚本到现在这功能就没能用过或者这是个新功能的请求
**您的浏览器和浏览器版本**：Chrome 50.0.2661.94 m (64-bit)
**您使用的猴子扩展的版本**：Tampermonkey v4.0.25
**您访问微博首页时的域名**：weibo.com
**微博网页中您设置的语言**：中文简体
**您访问微博时使用的网络**：其他地区
**您使用的微博网页的版本**：最近没改过版
**列出您安装的其他针对微博网站的脚本/样式/插件**：

**Comment by tiansh** [comment]
看来是因为 Chrome 没法识别 Data URI 里面的 &lt;meta charset&gt; 元素指定的字符编码……好像得改一下地址的样子……

**Comment by tiansh** [comment]
更新 381 试试，应该解决了……

多谢反馈！

**Comment by JayXon** [comment]
好了，谢谢
