### ISSUE TITLE
必须得是gm4？

### ISSUE THREAD

**Issue by blob2015** [tiansh/yawf#35]
目前浏览器停留在35，GM停留在3.3，发现YAWF好像部分失效了，看不到设置的按钮了

**Comment by blob2015** [comment]
不好意思，重装了一遍脚本，好了

**Comment by tiansh** [comment]
浏览器已知无法兼容 <20 的版本，没特意为旧版测试过。

目标支持的版本包括尚于支持期内的 ESR 版本到最新 beta 版本。其他的版本如果好修的话我会处理一下的。

如果没问题我就先关掉这个反馈了，如果再遇到问题请再留言和打开。
