### ISSUE TITLE
能否单独出个自动加载新微博脚本？

### ISSUE THREAD

**Issue by tulip33** [tiansh/yawf#36]
脚本功能太丰富强大了，其中的自动加载显示新微博功能很实用，能否精简一下单独出一个自动加载新微博功能的脚本？

**Comment by tiansh** [comment]
这个功能和脚本里面很多东西结合的比较多，很难单独拎出来，而且我也不想再另外维护另一个脚本。

话说回来，如果你安装这个脚本但只启用“自动加载新微博”的功能，会遇到什么问题吗？如果不是太麻烦的话，我可以把相关问题处理一下。

**Comment by tulip33** [comment]
启用这个脚本似乎会造成浏览微博卡顿的情况

**Comment by tiansh** [comment]
如果什么功能都没开就会卡顿的话我就算把这功能拎出来也不能保证不卡。那我就更懒得做这个了。
