### ISSUE TITLE
包含原图的网页里能否加入点击图片切换下一张的功能？

### ISSUE THREAD

**Issue by JayXon** [tiansh/yawf#37]
每次都要到左下角一张一张点挺麻烦的，希望可以直接点击图片切换下一张，如果能点击左半部分上一张，右半部份下一张那就更好了。

**Comment by tiansh** [comment]
我平时是用 [Firegestures](https://addons.mozilla.org/zh-CN/firefox/addon/firegestures/) 的url数字增加/减少1的功能来翻页的……

或许可以做一个点图片翻页的功能，类似幻灯放映那样。我考虑考虑。你觉得怎样的交互效果最好？

**Comment by JayXon** [comment]
其实就最简单的点击图片换到下一张就可以了，或者点击网页任意位置都切换也可以的。很多网站都有类似的功能，比如在android police随便找个文章点击里面的图片就会弹出一个悬浮窗可以查看所有图片，说到这个，其实我觉得不一定非要新建一个网页的，就像android police那样的悬浮窗也挺好的，方便切换回去。

**Comment by tiansh** [comment]
这个功能是“查看原图”，点击图片的功能是从“按原始大小显示图片”和“缩小到在当前屏幕下完整显示”这两个模式间切换。（当然，如果图片不如屏幕大，点击图片不会有反应）所以没法再安排一个点击图片翻页的功能。

至于你说的弹出悬浮框展示的功能，那个就是微博自己“查看大图”的功能吧，为什么还要用脚本的这个？

**Comment by JayXon** [comment]
因为微博自己的查看大图功能并不是原图？我感觉好像是不如原图清楚。
抱歉忘记了点击图片是切换放大缩小了，那如果做成点击图片边上的空白处切换上/下一张呢？

**Comment by tiansh** [comment]
加了一个简易的翻页功能，鼠标点图片左侧或右侧的位置可以翻页；第一页往前或最后一页往后翻会转到最后一页或第一页（绕回）。此外还可以用<kbd>PgUp</kbd>/<kbd>PgDown</kbd>按键翻页。
你觉得现在这样的设计怎么样？

**Comment by JayXon** [comment]
赞！有个小问题就是当鼠标在右侧的位置，变成一个`>`的时候，鼠标滚轮就失效了

**Comment by tiansh** [comment]
有道理，没注意这个问题，我看着处理一下……

**Comment by tiansh** [comment]
又改了改，现在应该会好一些……

抱歉最近比较忙，所以改得比较慢。

**Comment by JayXon** [comment]
现在可以了，非常感谢！
还有一个细节就是如果图片只有一张的话就没有必要添加这个翻页的区域了，不过这个倒是不重要啦
