### ISSUE TITLE
能否去除在添加Hashtag时出现的“想用什么话题”弹框？

### ISSUE THREAD

**Issue by pm2kjiagm** [tiansh/yawf#38]
![weibo](https://cloud.githubusercontent.com/assets/12817466/17358939/617e1304-599f-11e6-9231-0f09dfa0166c.png)
如图，在撰写微博框只要输入#，就会弹出这个框。能否添加一个功能将它去除？
非常感谢。

--
另：权宜之计是将“weibo.com/aj/mblog/topic”加入ABP的过滤列表中，即可阻止它出现。

**Comment by tiansh** [comment]
脚本可以隐藏掉这个框，但是脚本没法阻止微博将两个井号间的内容转换成话题。虽然你应该也很明白这个限制，但是把这个做成一个脚本的功能的话，很可能会引起别人的误会。

而且脚本如果要隐藏掉这个，能做的也就只有阻止这个网络访问成功。和你用 ABP 做到的差不了太多。

所以暂时没考虑把这个功能加到脚本里。

你能不能介绍一下你为什么希望有这个功能吗，因为框本来也不是一直都会出来，不是很扰民的那种。

**Comment by pm2kjiagm** [comment]
转换成Tag是没问题的，主要是不希望这个“热门”话题的列表出现。
因为当焦点在#后面的时候，按回车就会把最上面的话题自动填上去，而不是换行，很容易误操作（要换行需要先空格才行）。

**Comment by tiansh** [comment]
建议用 ABP 吧，脚本提供这个功能会很复杂。

**Comment by pm2kjiagm** [comment]
了解了，感谢。
