### ISSUE TITLE
版面清理—隐藏模块—导航栏 勾选游戏或发现屏蔽的都是发现板块

### ISSUE THREAD

**Issue by zixuan945** [tiansh/yawf#39]
**问题描述**：

版面清理—隐藏模块—导航栏 勾选游戏或发现屏蔽的都是发现板块

**相关设置**：

版面清理—隐藏模块—导航栏

**Comment by tiansh** [comment]
您好，我检查了一下这个问题，我这里没有问题。
请您首先检查一下脚本是否已经更新到了最新版（3.7.406）。由于导航栏刚刚改版，旧版脚本无法正确处理新版的导航栏。
如果仍有问题，希望可以导出一份设置[私信给我](http://weibo.com/yawfscript)，方便我检查问题所在。

**Comment by zixuan945** [comment]
@tiansh 确实是版本的问题 (现在更新了版本之后正常了，请问这个脚本是要手动更新吗？我在Tampermonkey的仪表盘勾选之后选择触发一个更新并没有更新到最新版本，在[Yet Another Weibo Filter 看真正想看的微博](https://greasyfork.org/zh-CN/scripts/3249-yet-another-weibo-filter)页面点击安装脚本也不会出现重新安装而是在下载js文件，下载后也不能安装，我是打开js复制并且替换了原来来安装的

**Comment by tiansh** [comment]
理论上会自动更新，不过因为自动更新会定期检查，所以不会非常及时。
不过你描述的情况更像是 Tampermonkey 坏掉了……
