### ISSUE TITLE
关于安装后无效

### ISSUE THREAD

**Issue by EillenS** [tiansh/yawf#40]
**问题描述**：

我更新了我的chrome浏览器，重新安装了几遍tampermonkey最新版，重新安装了几遍本脚本，但刷新or重启chrome软件后，微博还是未出现漏斗，并且tampermonkey未显示有运行的脚本，故障排除中几个都筛查了一下但还是未排除故障，球解救！QUQ

**Comment by tiansh** [comment]
您检查一下脚本是否安装成功了，能不能给个安装好的截图。

**Comment by tiansh** [comment]
长期没有反馈，先关掉了。如果还有问题，留言后点 Reopen 。
