### ISSUE TITLE
私信页面无法发图

### ISSUE THREAD

**Issue by nadjaNYX** [tiansh/yawf#41]
**问题描述**：

安装脚本后[私信页面](http://weibo.com/messages?topnav=1&wvr=6) 微博私信和群都无法发送图片，但右下的私信窗口可以。

**相关设置**：

配置为（但是正如下面将说明的，这不重要）

> {
>   "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
>   "yawf": "Yet Another Weibo Filter",
>   "ver": "3.7.417",
>   "gm": "Tampermonkey4.1.10",
>   "conf": {

>   }
> }

**操作步骤**：

某次更新脚本（就是那个可以禁用live photo功能的脚本）后出现这个问题。于是换网络，挂代理/不挂代理，在数个电脑（浏览器、扩展程序和脚本版本一致）上测试，都无法解决问题。
试图将YAWF所有勾选项去掉，配置变为

> {
>   "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
>   "yawf": "Yet Another Weibo Filter",
>   "ver": "3.7.417",
>   "gm": "Tampermonkey4.1.10",
>   "conf": {

>   }
> }

后，依旧不能再私信页面发图片，点击发图按键选好了图片以后确定完毫无反应。

唯一能解决问题的就是在暴力猴里禁掉了脚本再重新加载页面。

**期望结果**：

期望结果就可以发图片

**实际结果**：

跟没选发图的按键一样，好像发图是废了一样。

**以前的版本有这个问题吗**：
 脚本最近更新后出现的新问题，以前能用。大概是更新可以禁用live photo那个版本开始出现的问题。我基本是自动实时更新的
微博最近是否有改版不清楚。
**您的浏览器和浏览器版本**：Chrome 版本 53.0.2785.143 m（未在火狐上测试，如需要可以试一试）
**您使用的猴子扩展的版本**：Tampermonkey 4.1.10

**Comment by tiansh** [comment]
应该解决了。
