### ISSUE TITLE
[feature-request] 增加「微博评论默认显示热门，而非全部」的功能

### ISSUE THREAD

**Issue by waldens** [tiansh/yawf#42]
**问题描述**：

在「功能改造」中，能否增加「微博评论默认显示热门，而非全部」的功能？
因为微博评论繁多，通常「热门」的，才有阅读的价值。每次都要多点一下

**期望结果**：

希望启用该功能后，在微博主页、个人主页、单独微博页，点击「评论」后，显示「热门」评论，而非「全部」评论。

**附加信息**：

**您的浏览器和浏览器版本**：Firefox 最新版
**您使用的猴子扩展的版本**：Greasemonkey 最新版
**您访问微博首页时的域名**：www.weibo.com

**Comment by tiansh** [comment]
现在推“二级评论”（楼中楼）之后，是不是已经被默认改为“热门”了？

**Comment by waldens** [comment]
是的，「楼中楼」改版后，已经默认显示「热门」了 :)
