### ISSUE TITLE
包含原图的网页被Easylist误杀

### ISSUE THREAD

**Issue by JayXon** [tiansh/yawf#43]
**问题描述**：

点击缩略图后打开的新网页会立刻自动关闭

**相关设置**：
- [打开] 添加“查看原图”链接打开 包含原图的网页
- [打开] 点击缩略图时直接查看原图

**操作步骤**：

点击缩略图

**期望结果**：

打开包含原图的网页

**实际结果**：

网页打开后立刻自动关闭

**附加信息**：

**以前的版本有这个问题吗**：我不知道谁的问题，不过以前好好的最近出了问题
**您的浏览器和浏览器版本**：Chrome 54.0.2840.71 m (64-bit)
**您使用的猴子扩展的版本**：Tampermonkey® 4.1.10
**您访问微博首页时的域名**：weibo.com
**微博网页中您设置的语言**：中文简体
**您访问微博时使用的网络**：其他地区
**您使用的微博网页的版本**：最近没改过版
**列出您安装的其他针对微博网站的脚本/样式/插件**：

**Comment by tiansh** [comment]
关掉 ABP （或其他类似的广告屏蔽插件） 试试。

**Comment by JayXon** [comment]
关掉uBlock Origin之后好了。。。

**Comment by tiansh** [comment]
应该是 Easylist 的误杀，暂时没有什么比较好的办法。

**Comment by JayXon** [comment]
嗯找到了，Easylist里有条`data:text/html$popup`，貌似uBlock之前并不支持data:这种url，最近更新之后开始支持了。
我倒是有个想法，可以弹出一个类似 https://tiansh.github.io/yawf/gallery.html 这样的网址，然后里面已经包含各种网页的样式啊什么的，但是默认是没有任何图片的，然后用脚本动态的把图片加进去。

**Comment by tiansh** [comment]
是一个可以考虑的办法，有几个问题：
* 微博是否会限制页面的 referrer ？（ https 请求 http 的话应该送出来的是空 referrer 吧）
* GitHub是否会收集 *.github.io 站上的访问信息，这样做是否符合[脚本的隐私声明](https://tiansh.github.io/yawf/zh-cn.html#%E9%9A%90%E7%A7%81%E6%9D%83%E6%94%BF%E7%AD%96)

**Comment by JayXon** [comment]
- 嗯只要https不设置referrer的meta tag，默认是不会给http发送referrer的
- 不清楚是否会收集，反正这个功能并不是默认启用的，可以在选项那里给出提醒说GitHub有可能会收集信息

**Comment by tiansh** [comment]
换成 GM_openInTab 了，这个问题应该已经解决了。

**Comment by JayXon** [comment]
可以了，谢谢

**Comment by tiansh** [comment]
微博配图正常，但评论配图仍有问题。

**Comment by JayXon** [comment]
又出现这个问题了，这回是`|blob:$popup`

**Comment by tiansh** [comment]
正常，懒的管这个问题了。
