### ISSUE TITLE
微博转载文章跳转到源网址

### ISSUE THREAD

**Issue by SilverBut** [tiansh/yawf#44]
以[此链接](http://weibo.com/ttarticle/p/show?id=2309351002454044674699547450&u=1945921207&m=4044864474171607&cu=1945921207&ru=5044281310&rm=4044694906196244)的文章为例。该文章为新浪长微博从澎湃新闻的页面自动转换而来。这种自动转换还对其他部分站点有应用，目前观测到在部分网络情况差或排版特殊的站点中，这种文章部分图片不能正常加载，会被替换为带有“头条文章”水印的图片。

希望增加一个新特性，对这种微博文章，自动跳转到“查看源网址”对应的原文中。

我已经写了一个脚本，正在自用，如果有需要的话我可以帮忙加入到现有代码中。

**Comment by tiansh** [comment]
你觉得是自动跳转比较好，还是在点击链接的时候自动打开原网址比较好？

跳转的一个问题是，如果我临时不希望跳转，我就只能关掉脚本。而点击链接时自动打开原网址还可以通过类似“Shift-点击”这样的操作来回避。

看了一下相关微博，发现文章的链接和一般的文章无异，换句话说，肯定是需要一次网络请求才可以。不知道有没有比较方便的网络请求来做这个。

你自用的脚本目前是怎么的逻辑？

**Comment by SilverBut** [comment]
只是简单粗暴的：

    window.stop();
//...
    console.log(srcurl);
    window.location.href = srcurl;

因为是自用，所以没什么其他需求，直接跳飞了

想了想，一个可能有点糟糕的思路，点击的时候在当前页获取一下，然后跳。

2016-11-23 13:10 GMT+08:00 田生 <notifications@github.com>:

**Comment by tiansh** [comment]
看了一下，获取源站地址似乎只能先打开文章，有些复杂。

暂时先不考虑这个功能，看看需要的人多不多，多的话再说……
