### ISSUE TITLE
[Feature Request] macOS 平台添加使用系统字体选项

### ISSUE THREAD

**Issue by tzhao11** [tiansh/yawf#47]
macOS 上通过 `font-family: -apple-system` (Safari), `BlinkMacSystemFont` (Chrome) 可以让网页使用系统默认字体显示，这样可以启用系统字体的一些高级特性。

> 
> -  `-apple-system` targets San Francisco in Safari on Mac OS X and iOS, and it targets Neue Helvetica and Lucida Grande on older versions of Mac OS X. It properly selects between San Francisco Text and San Francisco Display depending on the text’s size.
> - `BlinkMacSystemFont` is the equivalent for Chrome on Mac OS X.

参考：

- https://www.zhihu.com/question/48451783

- https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/

**Comment by tiansh** [comment]
这和提供一个 `font-family: '.SFNSDisplay-Regular'` 有什么区别吗？

还有就是，使用 `font-family: -apple-system` 会对汉字造成影响吗，有以简体中文为主的网站这么写字体吗？

**Comment by tzhao11** [comment]
San Francisco 有两套字形，系统会根据字号自动切换，20pt 以下会切换到 San Francisco Text，对字符间距和其他细节有专门优化。另外在打了正确语言标记的网页上会选择最适合的字体显示，例如大陆简体使用苹方-简，香港繁体使用苹方-港，台湾繁体使用苹方-繁。

2016年12月12日 -0600 07:29 田生 <notifications@github.com>，写道：

**Comment by tzhao11** [comment]
另外苹果的 license 对 San Francisco 的使用范围好像有很严格的限制，但是用 apple system 和 blinkmacsystemfont 肯定是没问题的。还有直接使用 .SFNSDisplay-Regular 能正确处理粗体和斜体吗？

2016年12月12日 -0600 07:29 田生 <notifications@github.com>，写道：

**Comment by tzhao11** [comment]
看了 3.7.426 更新 使用 `-apple-system` 会让系统自动处理 font fallback 的问题，所以没必要区分中文和西文了。另外微博似乎没有`<lang>`标签，这种情况下中文字体应该是根据系统语言来的。

**Comment by tiansh** [comment]
系统自动处理替代字体无法适应现在脚本提供的设置项，而脚本的设置项并不是专门为 Mac 服务的，所以就像现在这样加好了。

粗体和斜体效果会不会变差我并不清楚，因为反正我没有苹果电脑。不过苹果自己没有暴露正常的字体名称的话，我也只能这样。

至于字体“使用范围”的问题，这并不在脚本的考虑范围内，因为使用范围是在“你的计算机”上，而不是我这，所以是否有适合的许可证并不是我要关心的问题。

**Comment by tzhao11** [comment]
建议把 `.SFNSDisplay-Regular` 换成 `.SFNSText-Regular`，因为微博大部分文字都在 20pt 以下，San Francisco Text 是专门为正文字号优化的。

目前我先用自定义 CSS 解决了。
`body, body.WB_macT, body.WB_xpT, .WB_webim {font-family: BlinkMacSystemFont;}`
