### ISSUE TITLE
未能过滤“有新的热门视频，点击查看”小黄签

### ISSUE THREAD

**Issue by ligyxy** [tiansh/yawf#49]
如同之前的热门微博小黄签，目前新有“热门视频”小黄签，该脚本尚不能过滤。

**Comment by tiansh** [comment]
感谢反馈。

已通过 e46d421092506dcdfbfd70d6042a41a557634221 更新。之前的“热门微博小黄签”该名成“热门黄签提醒”并加入了对热门视频的支持。
