### ISSUE TITLE
秒拍替换HTML5播放器功能貌似失效了？

### ISSUE THREAD

**Issue by YangJianchong** [tiansh/yawf#50]
Google Chrome	55.0.2883.95 (Official Build) (64-bit)
Revision	a97b1aab33877677c4734c58ed41246aa40942b7-refs/branch-heads/2883@{#738}
OS	Mac OS X 
JavaScript	V8 5.5.372.33
Flash	24.0.0.186

Yet Another Weibo Filter (YAWF) 3.7.432

**Comment by tiansh** [comment]
我这里没发现问题啊，可以给个出错的微博链接和操作步骤吗

**Comment by YangJianchong** [comment]
呃我这里现在正常了.再出现的话我再来反馈
