### ISSUE TITLE
在头条文章页面，yawf的图标显示成和消息图标一样了

### ISSUE THREAD

**Issue by nuzar** [tiansh/yawf#51]
http://weibo.com/ttarticle/p/show?id=2309404032815590172551
在这个页面发现的，如下图：
![2017-01-02 23 19 57](https://cloud.githubusercontent.com/assets/4602400/21591773/04579fc2-d142-11e6-87db-823293af0a38.png)
左边应该是过滤的图标

**Comment by tiansh** [comment]
应该解决了。
