### ISSUE TITLE
今天下午视频版面出了问题

### ISSUE THREAD

**Issue by Pason2C** [tiansh/yawf#52]
浏览器：Chrome 55.0.2883.87 m [Tampermonkey]
-----------------------------------------------------------------------------------------
使用配置为“[示例脚本配置](https://tiansh.github.io/yawf/sample-config.yawf)”
如图：
![1.jpg](https://ooo.0o0.ooo/2017/01/13/5878aba993c3b.jpg)
![2.jpg](https://ooo.0o0.ooo/2017/01/13/5878abab0c3b7.jpg)

另外再反映一个问题：
微博背景会遮挡微博内容（如图），这个如何过滤或屏蔽呢？
![3.jpg](https://ooo.0o0.ooo/2017/01/13/5878ad68c63b8.jpg)

**Comment by tiansh** [comment]
您好，感谢反馈。

作者这里无法复现您说的问题，这可能是因为部分功能微博分批推送导致的。

如果方便的话可否提供一个测试帐号，或者提供网页另存为后的结果（可以微博私信 @YAWF脚本 ）

另外，对于卡片背景遮挡的问题，可以隐藏卡片背景，在版面清理选项卡里面可以找到。

**Comment by Pason2C** [comment]
”网页另存为“已经通过微博私信发送至 @YAWF脚本。

**Comment by tiansh** [comment]
刚刚提交了针对这个问题的更新，希望可以解决问题。
