### ISSUE TITLE
能否实现基于通配符或正则，屏蔽一系列“原创帐号符合XX模式”的微博呢？

### ISSUE THREAD

**Issue by nagae-memooff** [tiansh/yawf#53]
比如，我想要屏蔽所有帐号名带有“吐槽君”字样的微博，目前由于是基于ID而不是帐号名匹配，似乎是做不到的。
以前眼不见心不烦可以直接以“关键词”屏蔽的形式去配置，对关键词、@提到、作者帐号名都会生效。

**Comment by tiansh** [comment]
你好，目前脚本没有将作者名和原作者名作为“内容”处理，也就无法通过针对内容的关键词进行过滤。

之前也有人有过类似的建议，也是因为之前用的 眼不见心不烦 所以有类似的需求。

不过一方面逻辑上用户名不是微博内容的一部分，另一方面现有的实现上要把用户名加进去会有些麻烦，所以一直也没打算做类似的修改。

也是因为会很麻烦，我还没有想好要不要添加作者名称作为内容的选项，也不知道这个功能的需求量会不会很大。

所以你觉得这个功能要怎么设计比较好，有什么想法吗。

（当然，在现有的脚本下，也是可以靠[额外写个小脚本](https://github.com/tiansh/xyawf)的方式来实现这个功能的）

**Comment by nagae-memooff** [comment]
感谢回复。我个人对这个功能怎么设计，其实没什么概念，我也并不确定我的这个需求是不是大家都想要。我先研究研究看是否能自己写个扩展先试试。

**Comment by gaomx** [comment]
会有因为某个方面的内容关注某个博主，但不想/不愿/没兴趣看ta其他方面内容的情况，所以希望可以针对某个具体用户的内容进行过滤，貌似这个需求跟楼主提到的类似。
之前试了下脚本提供的正则功能，无法满足。

**Comment by tiansh** [comment]
4.0 的正则会包含作者用户名。
