### ISSUE TITLE
"查看原图"弹出的新页面在浏览器重启后失效

### ISSUE THREAD

**Issue by aqaqaqq** [tiansh/yawf#54]
勾选以下两项：

- 添加“查看原图”链接打开包含原图的网页
- 点击缩略图时直接查看原图

点击图片时弹出的新页面，在刷新或浏览器重启或将其网址复制并在新页面粘贴并打开后失效，希望改进

![image](https://cloud.githubusercontent.com/assets/13092800/22599417/d8a65fd2-ea71-11e6-9e55-4bf6a03d48d9.png)

附加信息：
Chrome 56.0.2924.87 (64-bit)
Tampermonkey 4.2.7
简单测试后认为并非因为与其他插件或脚本冲突

**Comment by aqaqaqq** [comment]
没开发过Chrome插件，随意抛个砖，是不是太长的data:text/html地址会导致这样的问题发生？
能不能弄成类似
chrome-extension://fjnbnpbmkxxxxxxxxxxxxxxxxxeleoegfcffe/viewpic.html?pics=pic1_url|pic2_url|...
这样的？

**Comment by tiansh** [comment]
问题已知，这是一个 webkit 的 bug ： https://bugs.webkit.org/show_bug.cgi?id=68089

受影响的浏览器包括 Safari、Chrome 和 Opera 15+ ， Firefox 和 Opera 12 不受影响。

问题在于这些浏览器无法正确处理数据URI（Data URI）的锚点（hash）。

暂时不想修改这个问题，毕竟没觉得很重要。

**Comment by aqaqaqq** [comment]
原来如此，那就还是先这样用着了
