### ISSUE TITLE
Safari中无法正常使用账号屏蔽功能

### ISSUE THREAD

**Issue by RKNYC123** [tiansh/yawf#55]
大大好，我在Macbook的Safari上使用您的脚本时无法进行账号屏蔽。
手动输入账号后会显示“不存在名为xxx的账号”；使用拖拽功能时，拖拽的头像不能弹出提示窗口，拖拽微博账号链接虽然会弹出提示窗口，但同样显示“不存在名为xxx的账号”。
脚本版本号3.7.436，重装也无法解决。请大大帮忙解决，谢谢。
<img width="925" alt="screen shot 2017-03-02 at 9 08 29 pm" src="https://cloud.githubusercontent.com/assets/26155315/23536449/ecaff184-ffff-11e6-918f-ca48c2803813.png">

**Comment by RKNYC123** [comment]
现在发现拖拽功能成功率太低，拖二十次能成功一次就不错了。大多数时候把头像拖拽到黄色区域完全没有反应。

**Comment by tiansh** [comment]
这种情况可能是因为脚本无法正常访问网络，可以重新安装 Tampermonkey 试试。如果还有问题，我也不知道能怎么办了。
