### ISSUE TITLE
当微博自动打开兴趣推荐页面时，回到原页面

### ISSUE THREAD

**Issue by SpadeLushen** [tiansh/yawf#56]
有时候打开微博页面时，会跳转到兴趣推荐页面( http://weibo.com/nguide/interests )。
如果直接点击“进入微博”，就会关注选中的人。如果都不选中的话，就会提示“请至少选择一个兴趣标签”。只有手动重新输入网址，才能回到原来的页面。
希望能增加这样的功能，禁掉这个自动跳转，或者在跳转之后，再回到原页面。

**Comment by tiansh** [comment]
目前脚本的逻辑是在兴趣推荐页面不启用<sup>[\[1\]](https://github.com/tiansh/yawf/blob/master/Yet_Another_Weibo_Filter.user.js#L18)</sup>，原因是这个页面和其他的页面差别很大，脚本的功能会导致这个页面出问题。

暂时不考虑加这个功能，因为为了支持这个页面会影响现有的所有功能，太麻烦……

可以试试添加这么一个脚本，不过效果不确定（没试过……）

```javascript
// ==UserScript==
// @name        微博兴趣推荐页跳转到首页
// @namespace   https://github.com/tiansh/
// @include     http://weibo.com/nguide/*
// @version     1
// @grant       none
// ==/UserScript==

location.href = `//${location.host}`;
```

**Comment by SpadeLushen** [comment]
脚本有效

**Comment by SpadeLushen** [comment]
发现一个问题……
输入photo.weibo.com进入微博相册，也有几率跳转到兴趣推荐页面，使用这个脚本后就会跳转到微博首页……

**Comment by tiansh** [comment]
这个应该没什么办法吧，毕竟到了那个页面就没法知道是从哪里跳转过来的了……
