### ISSUE TITLE
firefox 更新至 52.0 后 漏斗图标消失 window.eval is not a function

### ISSUE THREAD

**Issue by mengyyy** [tiansh/yawf#57]
windows XP  sp2
firefox 52.0.0.6271
F12 调试显示
11:56:28.599 ERROR: Execution of script 'Yet Another Weibo Filter' failed! window.eval is not a function

**Comment by tiansh** [comment]
作者这里无法在 Windows 10 上的 Firefox 52.0.0 / 52.0.1 上复现这个问题。

手头没有 Windows XP ，暂时没法处理你这个问题。
