### ISSUE TITLE
现在用了脚本之后特别的卡Chrome 57/Edge 40

### ISSUE THREAD

**Issue by ChuHuaiJin** [tiansh/yawf#58]
现在用了脚本之后特别的卡Chrome 57/Edge 40
而且我还是禁用了flash的，卡的人难受
但是如果禁用了脚本之后就不卡了，很流畅

**Comment by tiansh** [comment]
脚本不支持 Edge 浏览器。

检查一下是不是打开的某个功能导致的，如果什么功能都不开也会卡的话个人建议直接卸载比较好。

附：[如何卸载脚本](https://tiansh.github.io/yawf/fqa.html#%E5%A6%82%E4%BD%95%E5%8D%B8%E8%BD%BD%E8%84%9A%E6%9C%AC)
