### ISSUE TITLE
Safari下脚本失效

### ISSUE THREAD

**Issue by gp04ddr** [tiansh/yawf#59]
脚本的设置无法保存

**Comment by Exodus000** [comment]
同样的问题，楼上是不是也更新了Tampermonkey...

**Comment by jzhang046** [comment]
这里同样的问题。Safari的Tampermonkey已经被更新到4.3，找了很久没找到旧版的4.2.7

**Comment by hydrowing** [comment]
更新了 Tampermonkey 后也出现了这个问题……

**Comment by tiansh** [comment]
有用户报告在更新系统、浏览器或 Tampermonkey 之后出现脚本无法正常运行的问题。

作者这并没在用 Mac ，所以也没法解决这问题。

如果有人愿意帮忙解决，这边欢迎拉取请求。

（如果实在没法解决，那我大概就只能把 Safari 从主页里去掉……

**Comment by Exodus000** [comment]
看了下Tampermonkey主页没给出4.3更新的详细内容
[但是好像有人报过bug](https://github.com/Tampermonkey/tampermonkey/issues)
我自己在console里试了一下似乎选项能读取和存储只是不显示在UI里，而且不管选不选都不会应用到网页，还有一个error是图里显示的这个
![8a47acba-b311-417e-a156-bef48df48784](https://cloud.githubusercontent.com/assets/14878589/24591470/bd736260-17b6-11e7-8db6-b435e65ff774.png)
![fe35932b-1ff0-485f-a64b-c27561245f08](https://cloud.githubusercontent.com/assets/14878589/24591471/c0999072-17b6-11e7-8bc0-4a01be7e74c3.png)
![7511e732-54b4-46a1-aaa5-3abadffdebc8](https://cloud.githubusercontent.com/assets/14878589/24591472/c30183f6-17b6-11e7-93e4-b6965497639b.png)
