### ISSUE TITLE
也是脚本特别卡，我看了控制台有报错

### ISSUE THREAD

**Issue by ColorfulNight** [tiansh/yawf#60]
VM90:5367 Uncaught TypeError: Cannot read property 'replace' of null
    at Object.expand (eval at E_c (:3:114), <anonymous>:5367:52)
    at Window.eval (eval at E_c (:3:114), <anonymous>:5327:75)
    at <anonymous>:2:297
    at e.string.c.(anonymous function) (eval at exec_fn (:1:108), <anonymous>:51:132)
expand	@	VM90:5367
(anonymous)	@	VM90:5327
(anonymous)	@	VM85:2
e.string.c.(anonymous function)	@	VM89:51

filter.items.base.autoload.auto_expand = filter.item({
  'group': 'autoload',
  'version': 46,
  'type': 'boolean',
  'key': 'weibo.other.auto_expand',
  'text': '{{autoExpand}}',
  'ref': {
    'i': { 'type': 'sicon', 'icon': 'ask', 'text': '{{autoExpandDesc}}' },
    'etypes': {
      'type': 'boolean',
    },
    'background': {
      'type': 'boolean',
      'default': true,
    },
  },
  'expand': function (feed, force) {
    var that = this;
    var display = feed.getAttribute('yawf-display').replace(/^.*-([^-]*)$/, '$1');//Uncaught TypeError: Cannot read property 'replace' of null
    var act = function () {
      var unreads = document.querySelectorAll('.WB_feed_type[yawf-unread="hidden"]');
      var ref = unreads[unreads.length - 1];
      ref.parentNode.insertBefore(feed, ref.nextSibling);
      feed.setAttribute('yawf-unread', 'show');
      filter.items.base.autoload.auto_load_new_weibo.counter();
    };
    if (feed.getAttribute('yawf-unread') !== 'hidden') return;
    if (force) return act();
    if (weibo.feed.author.id(feed) === util.info.uid) return act(); // 总是不折叠自己的微博
    if (!that.conf) return;
    if (that.ref.etypes.conf && display !== 'show') return;
    if (that.ref.background.conf && document.hasFocus()) {
      var onblur = function () {
        filter.items.base.autoload.auto_expand.expand(feed);
        document.removeEventListener('blur', onblur);
      };
      document.addEventListener('blur', onblur);
    } else act();
  },
}).addto(filter.groups.base);

`var display = feed.getAttribute('yawf-display').replace(/^.-([^-])$/, '$1');`
出问题的就这句

**Comment by tiansh** [comment]
您好，可否提供一下导出的配置。如果不方便贴在这里，可以在微博上私信脚本号或作者。感谢。

**Comment by ColorfulNight** [comment]
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36",
  "yawf": "Yet Another Weibo Filter",
  "ver": "3.7.436",
  "gm": "Tampermonkey4.2.7",
  "conf": {
    "weibo.tool.load_weibo_by_search": false,
    "weibo.tool.use_fast_creator": true,
    "weibo.tool.refilter": true,
    "weibo.tool.fast_hide_button": false,
    "weibo.tool.disable_lazyload": true,
    "weibo.other.group_account": false,
    "weibo.other.group_same_account": false,
    "weibo.other.auto_load_new_weibo": true,
    "weibo.other.auto_expand.etypes": false,
    "weibo.other.auto_expand.background": true,
    "weibo.other.auto_expand": false,
    "weibo.other.desktop_notification.types": true,
    "weibo.other.desktop_notification.autohide": true,
    "weibo.other.desktop_notification.shorten": false,
    "weibo.other.desktop_notification.shortlen": 50,
    "weibo.other.desktop_notification.duration": 3000,
    "weibo.other.desktop_notification.durationc": 150,
    "weibo.other.desktop_notification.ntypes": false,
    "weibo.other.desktop_notification": false,
    "weibo.filters.keyword.whitelist": [],
    "weibo.filters.keyword.blacklist": [],
    "weibo.filters.keyword.foldlist": [],
    "weibo.filters.regexp.whitelist": [],
    "weibo.filters.regexp.blacklist": [
      "BASTARZ",
      "段宜恩"
    ],
    "weibo.filters.regexp.foldlist": [],
    "weibo.content.types_mention": true,
    "weibo.content.types_topic": true,
    "weibo.content.types_stock": true,
    "weibo.content.types_linkt": true,
    "weibo.content.types_linku": false,
    "weibo.content.types_emotion": false,
    "weibo.filters.account.whitelist": [],
    "weibo.filters.account.blacklist": [
      "5543435229",
      "2273223252",
      "2263086932",
      "3217179555",
      "5923041063",
      "1729924375"
    ],
    "weibo.filters.account.foldlist": [],
    "weibo.filters.accountf.blacklist": [
      "1751035982",
      "2482557597",
      "1799454562",
      "5882998192",
      "3641513235",
      "2159931093",
      "2682256991",
      "5689988847",
      "1745746033",
      "1830442653"
    ],
    "weibo.filters.accountf.foldlist": [],
    "weibo.original.blacklist_d": true,
    "weibo.filters.original.whitelist": [],
    "weibo.filters.original.blacklist": [
      "1751035982",
      "2482557597",
      "1799454562",
      "5882998192",
      "3641513235",
      "1908531100",
      "2159931093",
      "2682256991",
      "5689988847",
      "1745746033",
      "1830442653",
      "5543435229",
      "2273223252",
      "2263086932",
      "3217179555",
      "5923041063",
      "1729924375"
    ],
    "weibo.filters.original.foldlist": [],
    "weibo.filters.mention.whitelist": [],
    "weibo.filters.mention.blacklist": [
      "田喜碧Hebe",
      "韩国me2day",
      "Ranee345",
      "Pony__朴惠敏",
      "锦鲤大王",
      "BlockB吧官博_BlockBBar",
      "南柱赫Club",
      "南柱赫吧",
      "王岳鹏Niko",
      "韩流音悦Tai",
      "19901214李敃赫资源博",
      "GOT7吧官博",
      "-禹丑丑",
      "回忆专用小马甲",
      "woozicoline",
      "杨杨阿宝"
    ],
    "weibo.filters.mention.foldlist": [],
    "weibo.filters.topic.whitelist": [],
    "weibo.filters.topic.blacklist": [],
    "weibo.filters.topic.foldlist": [],
    "weibo.filters.rtopic.whitelist": [],
    "weibo.filters.rtopic.blacklist": [
      "Block B",
      "BlockB",
      "光光の化妆教程",
      "田馥甄",
      "张艺兴",
      "段宜恩",
      "BASTARZ",
      "GOT7",
      "南柱赫"
    ],
    "weibo.filters.rtopic.foldlist": [],
    "weibo.filters.source.whitelist": [],
    "weibo.filters.source.blacklist": [],
    "weibo.filters.source.foldlist": [],
    "weibo.filters.hyperlink.whitelist": [],
    "weibo.filters.hyperlink.blacklist": [],
    "weibo.filters.hyperlink.foldlist": [],
    "weibo.filters.linktitle.whitelist": [],
    "weibo.filters.linktitle.blacklist": [],
    "weibo.filters.linktitle.foldlist": [],
    "weibo.other.my_weibo": false,
    "weibo.other.my_original": false,
    "weibo.other.mention_me": false,
    "weibo.other.ad_feed": true,
    "weibo.other.fans_top": true,
    "weibo.other.product_card": true,
    "weibo.other.tb_tm_wb": true,
    "weibo.other.weibo_pay_gift": true,
    "weibo.other.fake_weibo": true,
    "weibo.other.deleted_forward": true,
    "weibo.other.comment_and_reply": false,
    "weibo.other.vote_weibo": false,
    "weibo.other.red2014": false,
    "weibo.other.appitem": false,
    "weibo.other.wenwodr": true,
    "weibo.other.yizhibo.type": "all",
    "weibo.other.yizhibo": true,
    "weibo.other.stock": true,
    "weibo.other.multi_topic.num": 5,
    "weibo.other.multi_topic": true,
    "weibo.other.too_long": false,
    "weibo.other.wei_huati": false,
    "weibo.other.wei_qun": false,
    "weibo.other.wei_fangtan": false,
    "weibo.other.wei_gongyi": false,
    "weibo.other.unauth_source": false,
    "weibo.other.same_account.number": 5,
    "weibo.other.same_account.action": "fold",
    "weibo.other.same_account": false,
    "weibo.other.same_forward.number": 3,
    "weibo.other.same_forward.action": "fold",
    "weibo.other.same_forward": false,
    "weibo.filters.ckeyword.whitelist": [],
    "weibo.filters.ckeyword.blacklist": [],
    "weibo.filters.cregexp.whitelist": [],
    "weibo.filters.cregexp.blacklist": [
      "BASTARZ",
      "段宜恩"
    ],
    "weibo.filters.cuser.whitelist": [],
    "weibo.filters.cuser.blacklist": [
      "田喜碧Hebe",
      "韩国me2day",
      "Ranee345",
      "Pony__朴惠敏",
      "锦鲤大王",
      "BlockB吧官博_BlockBBar",
      "南柱赫Club",
      "南柱赫吧",
      "王岳鹏Niko",
      "韩流音悦Tai",
      "19901214李敃赫资源博",
      "GOT7吧官博",
      "-禹丑丑",
      "回忆专用小马甲",
      "woozicoline",
      "杨杨阿宝"
    ],
    "weibo.filters.ctopic.whitelist": [],
    "weibo.filters.ctopic.blacklist": [
      "Block B",
      "BlockB",
      "光光の化妆教程",
      "田馥甄",
      "张艺兴",
      "段宜恩",
      "BASTARZ",
      "GOT7",
      "南柱赫0222生日快乐"
    ],
    "weibo.comment.my_comment": true,
    "weibo.comment.emoji_count.number": 8,
    "weibo.comment.emoji_count": false,
    "weibo.comment.emoji_types.number": 4,
    "weibo.comment.emoji_types": false,
    "weibo.comment.no_content": false,
    "weibo.comment.with_forward": false,
    "weibo.comment.with_picture.act": "fold",
    "weibo.comment.with_picture": false,
    "weibo.comment.delete_comment": false,
    "weibo.layoutHideIconLevel": true,
    "weibo.layoutHideIconMember": true,
    "weibo.layoutHideIconApprove": false,
    "weibo.layoutHideIconApproveCo": false,
    "weibo.layoutHideIconApproveDead": true,
    "weibo.layoutHideIconClub": true,
    "weibo.layoutHideIconVGirl": true,
    "weibo.layoutHideIconTaobao": true,
    "weibo.layoutHideIconCheng": true,
    "weibo.layoutHideIconGongyi": true,
    "weibo.layoutHideIconSuishoupai": true,
    "weibo.layoutHideIconZongyika": true,
    "weibo.layoutHideIconYouji": true,
    "weibo.layoutHideIconDouble11": true,
    "weibo.layoutHideIconNight": true,
    "weibo.layoutHideIconRedPack": true,
    "weibo.layoutHideIconRun": true,
    "weibo.layoutHideIconFoolsDay": true,
    "weibo.layoutHideIconHong": true,
    "weibo.layoutHideIconWedding": true,
    "weibo.layoutHideNavLogoImg": true,
    "weibo.layoutHideNavMain": true,
    "weibo.layoutHideNavTV": true,
    "weibo.layoutHideNavHot": true,
    "weibo.layoutHideNavGame": true,
    "weibo.layoutHideNavHotSearch": true,
    "weibo.layoutHideNavNoticeNew": true,
    "weibo.layoutHideNavSettingNew": true,
    "weibo.layoutHideNavHotTip": true,
    "weibo.layoutHideLeftHome": false,
    "weibo.layoutHideLeftFav": false,
    "weibo.layoutHideLeftLike": false,
    "weibo.layoutHideLeftHot": true,
    "weibo.layoutHideLeftFriends": false,
    "weibo.layoutHideLeftGroupToMe": true,
    "weibo.layoutHideLeftSpecial": true,
    "weibo.layoutHideLeftWhisper": true,
    "weibo.layoutHideLeftNew": false,
    "weibo.layoutHideLeftNews": false,
    "weibo.layoutHideLeftCount": false,
    "weibo.layoutHideMiddleRecommendedTopic": true,
    "weibo.layoutHideMiddleFeedRecommand": true,
    "weibo.layoutHideMiddleMemberTip": true,
    "weibo.layoutHideRightInfo": false,
    "weibo.layoutHideRightRecomMusicRank": true,
    "weibo.layoutHideRightHotTopic": true,
    "weibo.layoutHideRightHotTopicExpand": true,
    "weibo.layoutHideRightInterest": true,
    "weibo.layoutHideRightMember": true,
    "weibo.layoutHideRightGroups": false,
    "weibo.layoutHideRightRecomGroupUser": true,
    "weibo.layoutHideRightHongbaoRank": true,
    "weibo.layoutHideRightMovie": true,
    "weibo.layoutHideRightAttFeed": false,
    "weibo.layoutHideRightTaobaoMovie": true,
    "weibo.layoutHideRightNotice": false,
    "weibo.layoutHideWeiboRecomFeed": false,
    "weibo.layoutHideWeiboFeedTip": false,
    "weibo.layoutHideWeiboGroupTip": false,
    "weibo.layoutHideWeiboVIPBackground": false,
    "weibo.layoutHideWeiboLastPic": false,
    "weibo.layoutHideWeiboPicTag": false,
    "weibo.layoutHideWeiboTopComment": false,
    "weibo.layoutHideWeiboSonTitle": false,
    "weibo.layoutHideWeiboCard": false,
    "weibo.layoutHideWeiboArticalPay": false,
    "weibo.layoutHideWeiboTag": false,
    "weibo.layoutHideWeiboMovieTag": false,
    "weibo.layoutHideWeiboSource": true,
    "weibo.layoutHideWeiboPop": false,
    "weibo.layoutHideWeiboLike": false,
    "weibo.layoutHideWeiboLikeComment": false,
    "weibo.layoutHideWeiboForward": false,
    "weibo.layoutHideWeiboFavourite": false,
    "weibo.layoutHideWeiboPromoteOther": false,
    "weibo.layoutHideWeiboReport": false,
    "weibo.layoutHideWeiboShield": false,
    "weibo.layoutHideWeiboUseCardBackground": false,
    "weibo.layoutHidePersonMoveThings": false,
    "weibo.layoutHidePersonCover": false,
    "weibo.layoutHidePersonBGImg": false,
    "weibo.layoutHidePersonBadgeIcon": false,
    "weibo.layoutHidePersonVerify": false,
    "weibo.layoutHidePersonEditPersonInfo": false,
    "weibo.layoutHidePersonStats": false,
    "weibo.layoutHidePersonMyData": false,
    "weibo.layoutHidePersonSuggestUser": false,
    "weibo.layoutHidePersonGroup": false,
    "weibo.layoutHidePersonRelation": false,
    "weibo.layoutHidePersonAlbum": false,
    "weibo.layoutHidePersonHotTopic": false,
    "weibo.layoutHidePersonHotWeibo": false,
    "weibo.layoutHidePersonUserList": false,
    "weibo.layoutHidePersonHongbao": false,
    "weibo.layoutHidePersonWenwoDr": false,
    "weibo.layoutHidePersonTimeline": true,
    "weibo.layout.pleft": [],
    "weibo.layoutHideMessagesHelp": false,
    "weibo.layoutHideMessagesFeedback": false,
    "weibo.layoutHideMessagesYoudao": false,
    "weibo.layoutHideOtherAds": true,
    "weibo.layoutHideOtherMusic": false,
    "weibo.layoutHideOtherTemplate": false,
    "weibo.layoutHideOtherHomeTip": false,
    "weibo.layoutHideOtherFooter": false,
    "weibo.layoutHideOtherWbIm": false,
    "weibo.layoutHideOtherIM": false,
    "weibo.layoutHideOtherTip": false,
    "weibo.layoutHideOtherRelatedWB": false,
    "weibo.layoutHideOtherRelatedArtical": false,
    "weibo.layoutHideOtherSendWeibo": false,
    "weibo.tool.showAllMsgNav.atme": true,
    "weibo.tool.showAllMsgNav.cmt": true,
    "weibo.tool.showAllMsgNav.like": false,
    "weibo.tool.showAllMsgNav.dm": true,
    "weibo.tool.showAllMsgNav.msgbox": true,
    "weibo.tool.showAllMsgNav.group": false,
    "weibo.tool.showAllMsgNav.dmsub": false,
    "weibo.tool.showAllMsgNav": true,
    "weibo.tool.showAllGroup": true,
    "weibo.tool.mergeColumns.side": "right",
    "weibo.tool.mergeColumns": false,
    "weibo.tool.chose_side.side": "right",
    "weibo.tool.chose_side": false,
    "weibo.tool.filte_right_topic": false,
    "weibo.tool.filte_right_topic_count.number": 200,
    "weibo.tool.filte_right_topic_count": false,
    "weibo.tool.right_user_list": [],
    "weibo.tool.right_user_list_notice": false,
    "weibo.tool.hide_nav_bar": false,
    "weibo.tool.fixedLeft": true,
    "weibo.tool.fixedRight": true,
    "weibo.tool.fixedNewFeedTip": false,
    "weibo.tool.fixedOthers": true,
    "weibo.tool.auto_unfold_weibo.count": 200,
    "weibo.tool.auto_unfold_weibo.br": 30,
    "weibo.tool.auto_unfold_weibo": true,
    "weibo.tool.clear_def_topic": true,
    "weibo.tool.redirectWeibo": true,
    "weibo.tool.public_by_default": false,
    "weibo.tool.cardButton": true,
    "weibo.tool.viewOriginal.open": "page",
    "weibo.tool.viewOriginal.direct": false,
    "weibo.tool.viewOriginal": true,
    "weibo.tool.noTagDialog": false,
    "weibo.tool.html5Video": true,
    "weibo.tool.replace_link": false,
    "weibo.tool.replace_image_emoji": false,
    "weibo.other.customize_source": false,
    "weibo.tool.auto_check_following.frequency": "1",
    "weibo.tool.auto_check_following": true,
    "weibo.tool.auto_unfold_ttartical": false,
    "weibo.tool.uncheck_follow_presenter": false,
    "weibo.tool.fast_emoji.top": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "weibo.tool.fast_emoji.recent": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "weibo.tool.fast_emoji": false,
    "weibo.tool.custom_font_family.wf": "Times New Roman",
    "weibo.tool.custom_font_family.cf": "微软雅黑",
    "weibo.tool.custom_font_family": true,
    "weibo.tool.weibo_large_font.ratio": "120",
    "weibo.tool.weibo_large_font": false,
    "weibo.tool.avatar_shape.shape": "square",
    "weibo.tool.avatar_shape": true,
    "weibo.tool.dark_nav_bar": true,
    "weibo.tool.reorder_nav_bar": false,
    "weibo.tool.nav_hide_name.act": "replace",
    "weibo.tool.nav_hide_name": false,
    "weibo.tool.width_weibo.width": 1080,
    "weibo.tool.width_weibo": true,
    "weibo.tool.weibo_only.width": 600,
    "weibo.tool.weibo_only.key": 119,
    "weibo.tool.weibo_only.switch": false,
    "weibo.tool.weibo_only": false,
    "weibo.tool.set_skin.skin": "skin058",
    "weibo.tool.set_skin": false,
    "weibo.tool.unwrapText": false,
    "weibo.tool.unwrapContent.text": "⏎",
    "weibo.tool.unwrapContent": false,
    "weibo.tool.image_size.repost": true,
    "weibo.tool.image_size": true,
    "weibo.tool.no_weibo_space": false,
    "weibo.tool.from_in_bottom": true,
    "weibo.tool.user_page_no_author.who": "all",
    "weibo.tool.user_page_no_author": true,
    "weibo.tool.hover_show_fold": false,
    "weibo.tool.fold_text.text": "author-reason",
    "weibo.tool.fold_text": false,
    "weibo.layout.reorder.1": "pop",
    "weibo.layout.reorder.2": "favorite",
    "weibo.layout.reorder.3": "forward",
    "weibo.layout.reorder.4": "comment",
    "weibo.layout.reorder.5": "like",
    "weibo.layout.reorder": true,
    "weibo.layout.cmtorder.1": "report",
    "weibo.layout.cmtorder.2": "delete",
    "weibo.layout.cmtorder.3": "conversition",
    "weibo.layout.cmtorder.4": "reply",
    "weibo.layout.cmtorder.5": "like",
    "weibo.layout.cmtorder": true,
    "weibo.tool.whitelist_highlight.color": "#dafee4",
    "weibo.tool.whitelist_highlight.transparency": 0,
    "weibo.tool.whitelist_highlight": false,
    "weibo.tool.color_override.color1": "#f6f6f6",
    "weibo.tool.color_override.transparency1": 30,
    "weibo.tool.color_override.color2": "#ffffff",
    "weibo.tool.color_override.transparency2": 30,
    "weibo.tool.color_override.color3": "#ffffff",
    "weibo.tool.color_override.transparency3": 30,
    "weibo.tool.color_override": false,
    "weibo.tool.userstyle": "",
    "script.other.auto_complete": false,
    "weibo.tool.disable_desktop_notification": true,
    "weibo.tool.disable_live_photo": false,
    "weibo.layoutHideLeftTV": true,
    "weibo.other.fold_child_comment": false,
    "weibo.other.comment_show_all": false,
    "weibo.other.wenda": true,
    "weibo.layoutHideNavNew": true
  }
}

**Comment by tiansh** [comment]
您好，我用您提供的那个配置文件试了一会儿，我这没看到报错的情况，所以不太确定是什么问题。

**Comment by ColorfulNight** [comment]
我换了暴力猴就好了，换之前还出现了脚本不工作的事情，就是那个漏斗也没有了

**Comment by tiansh** [comment]
我这两个宿主都试过，不过都没出问题。不过 TM 那边好像经常会有自动更新把自己玩挂的情况，原因不明。（总之好了就好）
