### ISSUE TITLE
打開"包含原圖的網頁"會閃退

### ISSUE THREAD

**Issue by bbsloj0416** [tiansh/yawf#65]
回報個bug~
在功能改造/添加「查看原圖」連結/ 若選擇【打開包含原圖的網頁】
點擊圖片時會開啟新分頁但是分頁會立即關閉(閃退)
選擇【原圖】的話倒沒有這個問題
希望能修復下
感謝

**Comment by tiansh** [comment]
请检查一下脚本、猴子是否是最新版。如果已经更新到了最新版仍然出现相同的问题，请提供如下信息：

1. 您的脚本的版本号
2. 运行脚本的猴子的名称和版本号
3. 您有没有安装任何广告屏蔽插件（如ABP）及他们的版本以及您订阅的规则
