### ISSUE TITLE
包含原图的网页无法切换图片

### ISSUE THREAD

**Issue by JayXon** [tiansh/yawf#66]
不知道怎么了，鼠标移动到最右侧点击毫无反应，直接点击下方的图片也不行，按page down也不行
Chrome 60，似乎是权限问题
![image](https://user-images.githubusercontent.com/1552641/28993607-81215784-796f-11e7-9b07-0e0ac2677270.png)

**Comment by edison0354** [comment]
同，广告屏蔽之类的能关的都关掉了也还是ls这个错误

之前win版没问题的，这几天在用Mac版发现有问题，手头没Win没法测试，不知道是不是Chrome更新出的问题……

**Comment by tiansh** [comment]
感谢反馈，原因是 Chrome 60 添加的“禁止导览到 data: 网址“的功能的一个小”bug(?)“导致的。受影响的用户为所有使用 Chrome 60+ 浏览器的用户。
