### ISSUE TITLE
脚本失效

### ISSUE THREAD

**Issue by FLEM1NGTON** [tiansh/yawf#67]
Windows10 Chrome下脚本失效 页面也没有漏斗标志
但Vivaldi下可以正常使用

版本
Chrome Beta 64位  61.0.3163.71
Tampermonkey 4.3.6
Yet Another Weibo Filter 3.7.453

**Comment by tiansh** [comment]
作者这边无法复现这种情况。

**Comment by tiansh** [comment]
无回应，先关了。有问题再留言再点打开。
