### ISSUE TITLE
建议将连续的被折叠微博合并在一起

### ISSUE THREAD

**Issue by AnnAngela** [tiansh/yawf#68]
RT，目前的表现并没有给人感受到折叠微博的好处，太占空间了：
![image](https://user-images.githubusercontent.com/9762652/30388420-3c44594e-98e2-11e7-8c76-68d266643c5a.png)

建议将其合并（以下为效果图）：
![image](https://user-images.githubusercontent.com/9762652/30388455-62a94c02-98e2-11e7-8ce8-b27f33dd3db5.png)

**Comment by tiansh** [comment]
可能冲突的功能：

1. 鼠标滑上时展开
    * 可能需要设置互斥？
2. 点击查看功能
    * 点击的时候一次将若干条展开吗？
3. 折叠微博显示折叠原因功能
    * 七条微博如何展示折叠原因？
4. 自动加载篇幅较长的微博
    * 这些微博的处理会推迟到获得微博原文之后，此时与上下已经有的折叠微博的合并操作会比较奇怪

**Comment by AnnAngela** [comment]
1. 应该需要设置互斥；
2. 是的，一次性展开；
3. 分别在其微博来源处显示？【来自 weibo网页端 （折叠原因：xxx）】
4. 展开后再自动加载？
