### ISSUE TITLE
时间线中出现长微博时插件失效

### ISSUE THREAD

**Issue by CSGA-KPX** [tiansh/yawf#69]
Vivaldi 1.10.867.48
Tampermonkey v4.4 
Yet Another Weibo Filte 3.7.453
https下访问微博

貌似在时间线内有长微博时，再刷新脚本失效，与是否展开无关。
失效后插件不加载，页面没有漏斗图标，类似 #67 

Tampermonkey中恢复出厂设置，再在插件中导入配置文件可以暂时恢复。
Tampermonkey中导出插件，修改Yet Another Weibo Filter.storage.json，删除long_weibo_cache字段后重新导入即可以暂时恢复。
不过暂时恢复以后碰到长微博会继续失效

附件为出现失效问题时的插件备份
[error.zip](https://github.com/tiansh/yawf/files/1308881/error.zip)

**Comment by tiansh** [comment]
Tampermonkey 的 bug，我这没法解决，等他们修。

**Comment by tiansh** [comment]
Vivaldi 可以装 暴力猴 吗？可以的话试试换那个，或者等他们什么时候修复吧。目测应该是长微博里面有个特殊字符，TM没有正确处理导致的。

**Comment by CSGA-KPX** [comment]
原来如此。 可以安装，已经换过去了。麻烦了。

**Comment by tiansh** [comment]
这边先开着，看看上游什么时候能处理……
