### ISSUE TITLE
转发微博的时候，被转发的微博如果带图片的话会出现一长串代码

### ISSUE THREAD

**Issue by jeremy1991310** [tiansh/yawf#71]
版本3.7.457
转发微博的时候，被转发的微博如果带图片的话会出现一长串代码，然后字数那里负9000多
如下边这样：
转发微博 a alt="http://t.cn/ROAia8l" suda-uatrack="key=transmit_pic&value=transmit_pic_minicard" href="data:text/html;charset=utf-8;base64,CjwhRE9DVFlQRSBodG1sPgo8aHRtbD4KPGhlYWQ+PG1ldGEgY2hhcnNldD0iVVRGLTgiIC8+PHRpdGxlPuafpeeci+WOn+WbviAtIFlBV0Y8L3RpdGxlPjxzdHlsZT4KYm9keSwgI2Nob
后边省略一千字……
![qq 20171006232333](https://user-images.githubusercontent.com/8223382/31285236-6b0be23e-aaed-11e7-8975-fd47c0532657.png)

**Comment by jeremy1991310** [comment]
感觉跟查看原图功能有关，后面的代码和查看原图的地址栏代码比较相似，不知道具体什么情况

**Comment by tiansh** [comment]
是的，是查看原图那边的问题。查看原图现在各种问题。更新一下试试，希望可以解决。

**Comment by jeremy1991310** [comment]
更新以后目前没有问题，转发正常了

**Comment by jeremy1991310** [comment]
持续用了几天，这个问题似乎没有再次出现过
