### ISSUE TITLE
明明没有勾选选项，却总是把个人主页里的关注粉丝微博数给屏蔽掉了

### ISSUE THREAD

**Issue by kiopkio** [tiansh/yawf#72]
好像是10月8日更新后才出现的
![sp171009_222536](https://user-images.githubusercontent.com/32643604/31343167-6618ac98-ad41-11e7-941d-e910e2754de4.png)

**Comment by tiansh** [comment]
抱歉，更新一下试试。

**Comment by kiopkio** [comment]
非常感谢，问题已经得到解决。
