### ISSUE TITLE
微博首页时间线在一定条数后突然错乱

### ISSUE THREAD

**Issue by jeremy1991310** [tiansh/yawf#73]
勾选了 使用搜索代替首页以恢复正常首页顺序
首页前面10-20条时间线什么的都正常，然后突然开始显示我自己之前发过的微博（按时间线排序的），后面全是自己发的微博，没有其他人的了。如图。
![wb1026](https://user-images.githubusercontent.com/8223382/32051100-ea879eac-ba85-11e7-8606-ddb5119932d2.jpg)

**Comment by jeremy1991310** [comment]
版本3.7.460

**Comment by tiansh** [comment]
试试刷新两次，再试试搜索一个双引号……

**Comment by jeremy1991310** [comment]
刷新两次，在第4页出现
![wb1026b](https://user-images.githubusercontent.com/8223382/32051854-d10fc2ee-ba88-11e7-8646-f6042a010aa9.jpg)
再刷新两次，在第3页出现

**Comment by jeremy1991310** [comment]
搜索双引号，在第9页出现
![wb1026c](https://user-images.githubusercontent.com/8223382/32051917-0830b5c6-ba89-11e7-888c-951eddd17dff.jpg)
再次搜索双引号，第4页出现
![wb1026d](https://user-images.githubusercontent.com/8223382/32052002-63617304-ba89-11e7-90a1-f6042d0880be.jpg)

**Comment by LoreYun** [comment]
我也遇到这个问题了。
有时候是打开网页第一条就开始是自己的。

**Comment by LoreYun** [comment]
3.7.461：还是有全是自己微薄的情况。
在第一页一开始就是自己微博的情况下，点开高级搜索，可以看到关键词处是两个英文单引号，开始日期是1970-01-02结束时间是今天。
点击搜索后，页面好像刷新了一下，然后关键词被清空，第一页上是没看见自己的微博了

**Comment by tiansh** [comment]
你看看浏览器地址栏里面的网址，和主页效果是否正常有什么因果关系吗。多刷新两次，如果有稳定的规律，可以在这里总结一下。

@LoreYun 不过从你说的情况来看，这基本上正常不正常只是随机赶上了……

**Comment by jeremy1991310** [comment]
3.7.461
这次自己的微博分别出现在第1、1、2页，
其中第二张图是滚轮往下翻分段加载的时候眼看着加载出自己的微博
![wb1101a](https://user-images.githubusercontent.com/8223382/32273853-2641f466-bf3f-11e7-83c1-f000d6d89911.png)
![wb1101b](https://user-images.githubusercontent.com/8223382/32273854-2682f15a-bf3f-11e7-8ac6-d7f310cc4bc0.png)
![wb1101c](https://user-images.githubusercontent.com/8223382/32273855-26bdbce0-bf3f-11e7-8e11-e3b7708acda5.png)

**Comment by jeremy1991310** [comment]
试了几次基本都出现了自己的微博，感觉是微博的搜索机制改变+分段加载导致的

**Comment by jeremy1991310** [comment]
关掉搜索替换主页选项以后手动搜索""，第8页出现，果然还是不行
![wb1101d](https://user-images.githubusercontent.com/8223382/32274106-59c7710c-bf40-11e7-80d5-c5e3bfaa5816.png)

**Comment by LoreYun** [comment]
3.7.461:
1.chrome的常用连接上打开的参数?wvr=5&lf=reg&is_search=1&key_word=%22
但是一进来第一页从头开始就是自己的。
2.点了一下最上面的首页，参数：?topnav=1&wvr=6&is_search=1&key_word=%22&start_time=1970-01-02&end_time=2038-01-19&gid=0
第一页变正常了，但是没往后看。
3.放了好久又点了下首页，参数：?topnav=1&wvr=6&is_search=1&key_word=%22&start_time=1970-01-02&end_time=2038-01-19&gid=0
参数和2相同，但是第一页一开始就又不正常了。

可能就是随机的。

**Comment by tiansh** [comment]
试试这个网址能正常使用吗： weibo.com/mygroups?gid=0

**Comment by LoreYun** [comment]
也不行，每次刷新，时间线的起始点都不一样。至于分组全不全就更不清楚了，少了谁的我自己也不知道，哈哈哈哈。

**Comment by jeremy1991310** [comment]
@tiansh weibo.com/mygroups?gid=0
这个地址的时间线目测跟不开脚本是一样的，会从2分钟前5分钟前突然跳到中午12点，上午10点

**Comment by tiansh** [comment]
移除了使用搜索代替首页的功能。
加了一个使用分组代替首页的功能。
分组有人数限制，所以我很不喜欢这个办法，不过似乎这是唯一好使的办法了。
