### ISSUE TITLE
使用多个分组拼凑首页无法工作

### ISSUE THREAD

**Issue by Kilo19** [tiansh/yawf#79]
我有数个分组，但勾选“使用多个分组拼凑首页”后点击添加时提示“{{{groupNotExistError}}}”

**Comment by tiansh** [comment]
感谢反馈。

第一个问题，提示信息不完整的问题会在后续尽快处理。

对于提示“分组不存在”，麻烦楼主试一下勾选“使用单个分组代替首页”的功能，然后看一下弹出的框能够正常显示您的分组列表吗。此外如果开启了输入框的自动补全，多个分组拼凑首页的输入框下面可以出现自动补全吗？

最后，请检查一下分组名称的书写是否一致，包括繁简体和英文大小写在内完全一致，不包含额外的空格等空白符号等。

**Comment by AzusA-Wu** [comment]
我也遇到了这个单个分组功能可以调出分组列表但是多个分组要调出分组列表时就会报分组不存在的BUG。
环境是Chrome 62.0.3202.94+暴力猴2.8.20

**Comment by tiansh** [comment]
刚刚的更新做了一些交互的修改，修复了显示的提示文字不正常的问题。

多个分组那个先点输入框，输入分组名称或从候选项中选择，再点添加按钮。交互逻辑类似于那个输入关键词以屏蔽的输入框。不要直接点添加按钮。
