### ISSUE TITLE
打开这个脚本后，整个微博卡的不行啊？

### ISSUE THREAD

**Issue by fengmikaelson** [tiansh/yawf#83]
滚动就跟没装显卡一样。。。
把脚本关了，就流畅了。。。
电脑配置应该没问题啊。。。

脚本是好脚本，我没有其他意思，不懂是不是我自己哪里没配置好？我反正就把不要的东西都选择屏蔽了。。。是不是功能开太多了？

**Comment by tiansh** [comment]
那就关掉吧，我也不知道为什么。

你开了哪些功能？
