### ISSUE TITLE
火狐浏览器打开"查看原图"会立刻自动关闭

### ISSUE THREAD

**Issue by yuaner66** [tiansh/yawf#85]
已经有好几天了，开始以为是其他的插件的问题，后来删掉配置文件重新安装后还是会出现这种问题。

浏览器版本：Firefox 59.0.1 (32 位)
猴子扩展的版本：暴力猴 2.8.30
脚本版本：Yet Another Weibo Filter (YAWF) 3.7.474
无其他任何附件组件也会出现这种问题。

**Comment by tiansh** [comment]
之前特别为火狐黑过，现在又他妈出问题了……

**Comment by tiansh** [comment]
请更新到 475 版本再试试。
