### ISSUE TITLE
Chrome 65 版本下脚本无效

### ISSUE THREAD

**Issue by YvanZ** [tiansh/yawf#86]
今天上午使用未更新的 Chrome 浏览器时，并没有注意脚本是否工作正常。
但是重启 Chrome 更新到 `65.0.3325.181` 后，确认该脚本已经无效。微博首页导航栏看不到漏斗的设置图标，微博页面也变回了原版。

**Comment by tiansh** [comment]
我这里 Chrome  65.0.3325.181，暴力猴 v2.8.30，脚本3.7.474，基本功能正常。

如果重装之类的操作无效，请报告具体的猴子版本、脚本版本、失效的功能。可以的话猴子里面把脚本连带设置导出出来然后微博上私信给我。

**Comment by YvanZ** [comment]
您好，我仔细看了一下，Tampermonkey v4.5 装的所有脚本均不正常了，应该是我这里的问题。
叨扰了，我关掉 issue 了
