### ISSUE TITLE
点击使用分组代替首页后弹出界面卡在正在获取分组信息界面

### ISSUE THREAD

**Issue by chenjiajia9411** [tiansh/yawf#87]
浏览器：Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0 ID:20180318203913
脚本管理器：暴力猴2.9 AMO
脚本版本：Yet Another Weibo Filter (YAWF) 3.7.474
已经关闭uBlock，NoScript等干扰附加组件。

1.几个规则订阅里的规则脚本的include和exclude都不支持https的微博了，望修正。
2.点击使用分组代替首页后弹出界面卡在正在获取分组信息界面。
控制台输出：
> 14:02:15.411 XHRURL:  //weibo.com/aj/f/group/list
home:2661:3
14:02:16.044
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More]
home:2735:22
onload
https://weibo.com/我的用户名/home:2735:22
n
https://weibo.com/我的用户名/home:3:22020
module.exports</t.a
https://weibo.com/我的用户名/home:3:22678
r
https://weibo.com/我的用户名/home:3:9234
module.exports</t.b/<
https://weibo.com/我的用户名/home:3:16071
d
moz-extension://a8c9eeea-f6d1-4d8e-9570-d180b22ab63d/injected.js:1:108
[26]/b.b/<
moz-extension://a8c9eeea-f6d1-4d8e-9570-d180b22ab63d/injected.js:1:466
[324]/b.d
moz-extension://a8c9eeea-f6d1-4d8e-9570-d180b22ab63d/injected.js:1:6366
[321]/b.a/<
moz-extension://a8c9eeea-f6d1-4d8e-9570-d180b22ab63d/injected.js:1:3673
apply self-hosted:4291:5 raw
resource://gre/modules/ExtensionCommon.jsm:1811:16
receiveMessage
resource://gre/modules/ExtensionChild.jsm:447:24
_callHandlers/responses<
resource://gre/modules/MessageChannel.jsm:870:16
map self-hosted:285:17 _callHandlers
resource://gre/modules/MessageChannel.jsm:868:21
_handleMessage/deferred.promise<
resource://gre/modules/MessageChannel.jsm:938:7
_handleMessage
resource://gre/modules/MessageChannel.jsm:935:24
_handleMessage self-hosted:977:17 receiveMessage/<
resource://gre/modules/MessageChannel.jsm:208:9
forEach self-hosted:261:13 receiveMessage
resource://gre/modules/MessageChannel.jsm:201:5
14:02:18.016 unreachable code after return statement[Learn More]
webim.js:172:1823
14:02:18.017 unreachable code after return statement[Learn More]
webim.js:174:1984
14:02:18.026 unreachable code after return statement[Learn More]
webim.js:198:103
14:02:18.027 unreachable code after return statement[Learn More]
webim.js:200:87
14:02:18.028 unreachable code after return statement[Learn More]
webim.js:207:87
14:02:18.045 unreachable code after return statement[Learn More]
webim.js:139:984
14:02:29.638
GET
https://rm.api.weibo.com/2/remind/push_count.json?trim_null=1&with_dm_group=0&with_settings=1&exclude_attitude=1&with_common_cmt=1&with_comment_attitude=1&with_common_attitude=1&with_moments=1&with_dm_unread=1&msgbox=true&with_page_group=1&with_chat_group=1&with_chat_group_notice=1&_pid=1&count=5&source=351354573&status_type=0&callback=STK_152282162370044
[HTTP/1.1 200 OK 65ms]
14:02:29.674 performance meansure:  
Object { weiboObserver: {…}, commentObserver: {…}, markCommentButton: {…}, markPictureViewButton: {…}, tagModsInner: {…}, tagMods: {…}, updateSkin: {…}, noAdsRemoveClassName: {…}, removeRightFixed: {…}, markLinkType: {…}, … }
home:1491:7
14:02:59.548
GET
https://rm.api.weibo.com/2/remind/push_count.json?trim_null=1&with_dm_group=0&with_settings=1&exclude_attitude=1&with_common_cmt=1&with_comment_attitude=1&with_common_attitude=1&with_moments=1&with_dm_unread=1&msgbox=true&with_page_group=1&with_chat_group=1&with_chat_group_notice=1&_pid=1&count=6&source=351354573&status_type=0&callback=STK_152282162370046
[HTTP/1.1 200 OK 65ms]

**Comment by tiansh** [comment]
如果这个问题可以反复出现，在出现同样问题之后，浏览器地址栏里面输入 `https://weibo.com/aj/f/group/list` 打开新页面，这个页面显示的内容正常吗？

正常的话内容应该类似于
```json
{"code":"100000","msg":"","data":[{"gid":"********************","gname":"\u7279\u522b\u5173\u6ce8","mode":"system","visible":-1,"desc":"","belong":0,"is_important_group":1},...]}
```

**Comment by chenjiajia9411** [comment]
内容是正常的……

**Comment by kalteblau** [comment]
微博网页版点击管理关注列表那边本身显示正常，在这个页面脚本还是没法获得分组信息。

今天把脚本的调试打开看了一下，改了错误信息了：
read GM value                                   home:2309:5
write GM value                                  home:2315:5
XHRURL:  //www.weibo.com/aj/f/group/list                         home:2753:3
SyntaxError: JSON.parse: unexpected character at line 2 column 3 of the JSON data            home:2830:22

我本来也想通过调试器看一下代码执行情况，奈何自身水平有限玩不转Web。Firefox的F12似乎无法显示暴力猴加载的脚本。。我不能找到一种合适的调试方式

在首页点击获得分组信息和在其他页面点击是一样的，报错一致。

**Comment by tiansh** [comment]
目前看来应该有最新微博了这个不怎么用得到……
