### ISSUE TITLE
图标显示不出来

### ISSUE THREAD

**Issue by mzfe** [tiansh/yawf#88]
win7 64位
firefox 59.0.2 64位
版本 3.7.474

console输出：
ReferenceError
​
columnNumber: 11
​
fileName: "resource://gre/modules/ExtensionContent.jsm"
​
lineNumber: 1857
​
message: "GM_getValue is not defined"
​
stack: "userScript/util.script.isdebug<@user-script:https%3A//github.com/tiansh/Yet%20Another%20Weibo%20Filter:1857:11\nuserScript@user-script:https%3A//github.com/tiansh/Yet%20Another%20Weibo%20Filter:1855:24\nscopeWrapper@user-script:https%3A//github.com/tiansh/Yet%20Another%20Weibo%20Filter:12713:9\n@user-script:https%3A//github.com/tiansh/Yet%20Another%20Weibo%20Filter:487:17\n"
​
__proto__: {…}
​​
constructor: function ReferenceError()
​​
message: ""
​​
name: "ReferenceError"
​​
stack: ""
​​
__proto__: Object { … }

**Comment by tiansh** [comment]
你是不是用了 GreaseMonkey？
这个脚本只支持 ViolentMonkey 和 Tampermonkey ，暂无无支持 Greasemonkey 的计划。

**Comment by mzfe** [comment]
是的，原来不支持油猴子了。已更换
