### ISSUE TITLE
不登陆微博不能正常显示微博内容

### ISSUE THREAD

**Issue by etjim** [tiansh/yawf#89]
本人在Firefox上使用Violentmonkey运行该本脚的，但在使用上出现了一点小问题。一经登陆微博，然后退出登陆微博，再次访问任意微博主页都无法显示微博主要内容。本人已经新建Firefox配置文件反复测试，都100%出现这个问题。但改用TamperMonkey就没有此问题，不论登不登陆微博都能正常显示微博主要内容。请问这时脚本问题还是Violentmonkey问题。

浏览器：Firefox 60b12
脚本管理器：Violentmonkey 2.9.1

**Comment by tiansh** [comment]
脚本并非针对未登录的情况准备的，望见谅。

**Comment by tiansh** [comment]
4.0 应该可以了（大概）
