### ISSUE TITLE
如果能添加避免异常点赞的功能

### ISSUE THREAD

**Issue by greentree20007** [tiansh/yawf#90]
每天都有一堆莫名其妙的点赞……

**Comment by tiansh** [comment]
当我有新的点赞时像新加了关注一样给个弹框？

**Comment by ewgasdf** [comment]
这个是微博官方盗号，脚本管不了233

**Comment by ShimotsukiH** [comment]
建议删除所有授权+利用lastpass替换高安全性随机密码
我这边这样操作后基本没有莫名其妙的赞
取消授权 https://weibo.com/1457585272/GvNspv5TT?ref=home&rid=5_0_0_4726398977178575503_0_0
lastpass介绍 https://sspai.com/post/26418
