### ISSUE TITLE
查看原图的标签页被AdBlock拦截

### ISSUE THREAD

**Issue by lidoworld** [tiansh/yawf#91]
「查看图片添加“查看原图”链接」 中如果选择 「打开“包含原图的网页”」，那么在点击按钮后弹出的标签页会被AdBlock瞬间关闭。
如果停用AdBlock 现象消失，如果选择「打开“原图”」没有问题。

应该是最新版本才有的现象。
Chrome 66.0.3359.117
暴力猴 v2.9.4
Yet Another Weibo Filter 3.7.475
AdBlock 3.28.0

**Comment by tiansh** [comment]
正常情况，不打算处理。
