### ISSUE TITLE
“多个分组拼凑首页”功能更新后无法显示“特别关注”分组中的微博

### ISSUE THREAD

**Issue by Franinc** [tiansh/yawf#93]
更新前可以在“多个分组拼凑首页”下的“选择分组”中添加“特别关注”这个分组，更新后无法再添加，同时也不会再显示“特别关注”下的微博。
问题原因：老版本能添加“特别关注”时加了进去，新版本的“选择分组”下面方框里不显示“特别关注”四个之只剩下x键，刚才没注意顺手就删了，所以也就不再显示“特别关注”组下的微博了。
自己把“特别关注”组的gid加回去就修好了。

希望作者能把“特别关注”这个组加回到“选择分组”中，因为没有脚本的微博只有组的时间线才时正常的，当时为了省事把200个关注都放在了特别关注里……感谢！

**Comment by tiansh** [comment]
其实和这次改的没关系，之前“特别关注”和其他分组时在一起的，所以不用单独处理。现在网页上，特别关注整个被拆出去了，所以不在以前的列表里展现了……

**Comment by tiansh** [comment]
暂时没有什么办法可以拿到特别关注的组号，所以并不知道该怎么处理……

**Comment by tiansh** [comment]
现在特别关注应该回来了。
这期间我什么都没做……
（双手离开键盘以示清白……
