### ISSUE TITLE
微博打开 无法登陆页面 提示如下 关闭脚本就好了

### ISSUE THREAD

**Issue by Xhyen** [tiansh/yawf#94]
414 Request-URI Too Large
The requested URL's length exceeds the capacity limit for this server. Sorry for the inconvenience.
Please report this message and include the following information to us.
Thank you very much!

**Comment by tiansh** [comment]
麻烦详细描述一下复现步骤：打开的什么网址？打开之后点了什么？然后出现了什么情况？出错页面的网址是什么？

**Comment by Xhyen** [comment]
@tiansh 今天测试了下暂时没有出现问题。下次如果再出现我完整提一下~

**Comment by Xhyen** [comment]
今天早上出现该问题了，我打开了微博，浏览器其余页面是昨天打开留着的，然后我点开一个微博id想进去看详情。然后弹出该错误，url是https://weibo.com/u/6150420167?refer_flag=0000015012_&from=feed&loc=nickname

**Comment by Xhyen** [comment]
URL: | http://weibo.com/u/6150420167?refer_flag=0000015012_&from=feed&loc=nickname
-- | --
Server: | venus245
Date: | 2018/05/24 08:36:15

**Comment by Xhyen** [comment]
报错内容相同

**Comment by Xhyen** [comment]
414 Request-URI Too Large
The requested URL's length exceeds the capacity limit for this server. Sorry for the inconvenience.
Please report this message and include the following information to us.
Thank you very much!

URL: | http://weibo.com/u/6150420167?refer_flag=0000015012_&from=feed&loc=nickname
-- | --
Server: | venus245
Date: | 2018/05/24 08:36:15

**Comment by Xhyen** [comment]
以下是报错页面截图
![image](https://user-images.githubusercontent.com/17582511/40458355-24550d70-5f2e-11e8-92b7-bf6372bb0c92.png)

**Comment by Xhyen** [comment]
如果立即刷新页面是同样报错，如果等一会刷新，页面就正常跳转了

**Comment by tiansh** [comment]
没办法确认这个问题，不过也收到过其他人类似的报告。可否复查一下是不是因为和其他哪个插件/脚本冲突导致的？
