### ISSUE TITLE
添加自动检查其他账号的关注等操作的功能

### ISSUE THREAD

**Issue by zyjzhzyh** [tiansh/yawf#95]
近日在论坛、微博大家多有抱怨某些特别三观不合的微博，常常有人说类似这样的话：“关注了某某某的人请和我相互拉黑”、“我真想拉黑某某某条微博下的评论”，比如近日各种夺人眼球的营销号如ayawawa，同时具有相同兴趣的网民关注的账号也多有重合，我因此突发奇想，认为了解微博网友的关注和评论/点赞/转发是一个很方便精确地观察网友的好方法，不但可以用来辨别虚拟世界他人的兴趣和三观还可以用来寻找同好，当然网站站长可以轻易通过后台数据/跟踪脚本做到这一点，但是普通网友手段很有限，而大多数微博账号关注数量太大，少则几百，多则上千，如果人工翻找粉丝列表太过麻烦，那么，如果有一个脚本可以做到这样的功能：

使用者将自己极其讨厌/极其喜欢的某个账号列为监视项目，并且检索某网友是否关注了这个账号，这点能否通过匹配一个账号的粉丝列表和另一个账号的关注列表来实现？并且进一步，如果还能将一条微博的点赞/转发/评论列为监视项目就更好了。

我是个外行，或许微博没有开通这样的权限，如果可行，这个功能还能用来对网友画像，不论是否可行，烦请作者回复告知。

**Comment by tiansh** [comment]
别人的关注列表只能拿到前 200 个，目前唯一一个检查某人（张三）是否关注了另一个人（李四）的方式是你也关注李四，然后看你和张三的共同关注。这事情脚本也没办法做到。而且这个功能势必要大量翻各种页面，请求太不友好了，所以也暂无计划。

之前有过考虑的功能是统计首页上被脚本隐藏的微博的作者……不过这个只是这么一说，因为不知道会不会有任用，目前也没有做的打算……
