### ISSUE TITLE
功能建议：“包含原图的网页”可用键盘方向键翻页

### ISSUE THREAD

**Issue by Hubedge** [tiansh/yawf#98]
如题

**Comment by tiansh** [comment]
目前可以用 <kbd>PgUp</kbd> / <kbd>PgDn</kbd> 翻页，用 <kbd>1</kbd> ~ <kbd>9</kbd> 快速跳转到某页。
当图片的尺寸超过展示区域时，方向键被用于卷动滚动条。
所以暂不考虑使用方向键翻页。

**Comment by Hubedge** [comment]
原来如此，谢谢！另，希望这些用法能在设置页中相应位置提示一下。

**Comment by tiansh** [comment]
设置页面已经够乱的了，而且这个不知道也不影响正常使用，所以还是算了吧……
